package foo.sample.db.auto.ref.model;

public class CatvSp許諾Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_SP許諾.CATV_CD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String catvCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_SP許諾.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String spId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_SP許諾.CATV_CD
     *
     * @return the value of CATV_SP許諾.CATV_CD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getCatvCd() {
        return catvCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_SP許諾.CATV_CD
     *
     * @param catvCd the value for CATV_SP許諾.CATV_CD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setCatvCd(String catvCd) {
        this.catvCd = catvCd == null ? null : catvCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_SP許諾.SP_ID
     *
     * @return the value of CATV_SP許諾.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_SP許諾.SP_ID
     *
     * @param spId the value for CATV_SP許諾.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setSpId(String spId) {
        this.spId = spId == null ? null : spId.trim();
    }
}