package foo.sample.db.auto.ref.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CatvSp許諾Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public CatvSp許諾Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCatvCdIsNull() {
            addCriterion("CATV_CD is null");
            return (Criteria) this;
        }

        public Criteria andCatvCdIsNotNull() {
            addCriterion("CATV_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCatvCdEqualTo(String value) {
            addCriterion("CATV_CD =", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotEqualTo(String value) {
            addCriterion("CATV_CD <>", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdGreaterThan(String value) {
            addCriterion("CATV_CD >", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdGreaterThanOrEqualTo(String value) {
            addCriterion("CATV_CD >=", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLessThan(String value) {
            addCriterion("CATV_CD <", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLessThanOrEqualTo(String value) {
            addCriterion("CATV_CD <=", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLike(String value) {
            addCriterion("CATV_CD like", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotLike(String value) {
            addCriterion("CATV_CD not like", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdIn(List<String> values) {
            addCriterion("CATV_CD in", values, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotIn(List<String> values) {
            addCriterion("CATV_CD not in", values, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdBetween(String value1, String value2) {
            addCriterion("CATV_CD between", value1, value2, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotBetween(String value1, String value2) {
            addCriterion("CATV_CD not between", value1, value2, "catvCd");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNull() {
            addCriterion("SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(String value) {
            addCriterion("SP_ID =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(String value) {
            addCriterion("SP_ID <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(String value) {
            addCriterion("SP_ID >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ID >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(String value) {
            addCriterion("SP_ID <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ID <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLike(String value) {
            addCriterion("SP_ID like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotLike(String value) {
            addCriterion("SP_ID not like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<String> values) {
            addCriterion("SP_ID in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<String> values) {
            addCriterion("SP_ID not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(String value1, String value2) {
            addCriterion("SP_ID between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(String value1, String value2) {
            addCriterion("SP_ID not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria and事業者コードIsNull() {
            addCriterion("事業者コード is null");
            return (Criteria) this;
        }

        public Criteria and事業者コードIsNotNull() {
            addCriterion("事業者コード is not null");
            return (Criteria) this;
        }

        public Criteria and事業者コードEqualTo(String value) {
            addCriterion("事業者コード =", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードNotEqualTo(String value) {
            addCriterion("事業者コード <>", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードGreaterThan(String value) {
            addCriterion("事業者コード >", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードGreaterThanOrEqualTo(String value) {
            addCriterion("事業者コード >=", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードLessThan(String value) {
            addCriterion("事業者コード <", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードLessThanOrEqualTo(String value) {
            addCriterion("事業者コード <=", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードLike(String value) {
            addCriterion("事業者コード like", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードNotLike(String value) {
            addCriterion("事業者コード not like", value, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードIn(List<String> values) {
            addCriterion("事業者コード in", values, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードNotIn(List<String> values) {
            addCriterion("事業者コード not in", values, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードBetween(String value1, String value2) {
            addCriterion("事業者コード between", value1, value2, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者コードNotBetween(String value1, String value2) {
            addCriterion("事業者コード not between", value1, value2, "事業者コード");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidIsNull() {
            addCriterion("事業者ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidIsNotNull() {
            addCriterion("事業者ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidEqualTo(String value) {
            addCriterion("事業者ユーザID =", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidNotEqualTo(String value) {
            addCriterion("事業者ユーザID <>", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidGreaterThan(String value) {
            addCriterion("事業者ユーザID >", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("事業者ユーザID >=", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidLessThan(String value) {
            addCriterion("事業者ユーザID <", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidLessThanOrEqualTo(String value) {
            addCriterion("事業者ユーザID <=", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidLike(String value) {
            addCriterion("事業者ユーザID like", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidNotLike(String value) {
            addCriterion("事業者ユーザID not like", value, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidIn(List<String> values) {
            addCriterion("事業者ユーザID in", values, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidNotIn(List<String> values) {
            addCriterion("事業者ユーザID not in", values, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidBetween(String value1, String value2) {
            addCriterion("事業者ユーザID between", value1, value2, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者ユーザidNotBetween(String value1, String value2) {
            addCriterion("事業者ユーザID not between", value1, value2, "事業者ユーザid");
            return (Criteria) this;
        }

        public Criteria and事業者idIsNull() {
            addCriterion("事業者ID is null");
            return (Criteria) this;
        }

        public Criteria and事業者idIsNotNull() {
            addCriterion("事業者ID is not null");
            return (Criteria) this;
        }

        public Criteria and事業者idEqualTo(String value) {
            addCriterion("事業者ID =", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idNotEqualTo(String value) {
            addCriterion("事業者ID <>", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idGreaterThan(String value) {
            addCriterion("事業者ID >", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idGreaterThanOrEqualTo(String value) {
            addCriterion("事業者ID >=", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idLessThan(String value) {
            addCriterion("事業者ID <", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idLessThanOrEqualTo(String value) {
            addCriterion("事業者ID <=", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idLike(String value) {
            addCriterion("事業者ID like", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idNotLike(String value) {
            addCriterion("事業者ID not like", value, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idIn(List<String> values) {
            addCriterion("事業者ID in", values, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idNotIn(List<String> values) {
            addCriterion("事業者ID not in", values, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idBetween(String value1, String value2) {
            addCriterion("事業者ID between", value1, value2, "事業者id");
            return (Criteria) this;
        }

        public Criteria and事業者idNotBetween(String value1, String value2) {
            addCriterion("事業者ID not between", value1, value2, "事業者id");
            return (Criteria) this;
        }

        public Criteria and代表事業者FIsNull() {
            addCriterion("代表事業者_F is null");
            return (Criteria) this;
        }

        public Criteria and代表事業者FIsNotNull() {
            addCriterion("代表事業者_F is not null");
            return (Criteria) this;
        }

        public Criteria and代表事業者FEqualTo(String value) {
            addCriterion("代表事業者_F =", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FNotEqualTo(String value) {
            addCriterion("代表事業者_F <>", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FGreaterThan(String value) {
            addCriterion("代表事業者_F >", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FGreaterThanOrEqualTo(String value) {
            addCriterion("代表事業者_F >=", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FLessThan(String value) {
            addCriterion("代表事業者_F <", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FLessThanOrEqualTo(String value) {
            addCriterion("代表事業者_F <=", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FLike(String value) {
            addCriterion("代表事業者_F like", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FNotLike(String value) {
            addCriterion("代表事業者_F not like", value, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FIn(List<String> values) {
            addCriterion("代表事業者_F in", values, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FNotIn(List<String> values) {
            addCriterion("代表事業者_F not in", values, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FBetween(String value1, String value2) {
            addCriterion("代表事業者_F between", value1, value2, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and代表事業者FNotBetween(String value1, String value2) {
            addCriterion("代表事業者_F not between", value1, value2, "代表事業者F");
            return (Criteria) this;
        }

        public Criteria and開始有効日時IsNull() {
            addCriterion("開始有効日時 is null");
            return (Criteria) this;
        }

        public Criteria and開始有効日時IsNotNull() {
            addCriterion("開始有効日時 is not null");
            return (Criteria) this;
        }

        public Criteria and開始有効日時EqualTo(Date value) {
            addCriterion("開始有効日時 =", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時NotEqualTo(Date value) {
            addCriterion("開始有効日時 <>", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時GreaterThan(Date value) {
            addCriterion("開始有効日時 >", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時GreaterThanOrEqualTo(Date value) {
            addCriterion("開始有効日時 >=", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時LessThan(Date value) {
            addCriterion("開始有効日時 <", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時LessThanOrEqualTo(Date value) {
            addCriterion("開始有効日時 <=", value, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時In(List<Date> values) {
            addCriterion("開始有効日時 in", values, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時NotIn(List<Date> values) {
            addCriterion("開始有効日時 not in", values, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時Between(Date value1, Date value2) {
            addCriterion("開始有効日時 between", value1, value2, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and開始有効日時NotBetween(Date value1, Date value2) {
            addCriterion("開始有効日時 not between", value1, value2, "開始有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時IsNull() {
            addCriterion("終了有効日時 is null");
            return (Criteria) this;
        }

        public Criteria and終了有効日時IsNotNull() {
            addCriterion("終了有効日時 is not null");
            return (Criteria) this;
        }

        public Criteria and終了有効日時EqualTo(Date value) {
            addCriterion("終了有効日時 =", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時NotEqualTo(Date value) {
            addCriterion("終了有効日時 <>", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時GreaterThan(Date value) {
            addCriterion("終了有効日時 >", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時GreaterThanOrEqualTo(Date value) {
            addCriterion("終了有効日時 >=", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時LessThan(Date value) {
            addCriterion("終了有効日時 <", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時LessThanOrEqualTo(Date value) {
            addCriterion("終了有効日時 <=", value, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時In(List<Date> values) {
            addCriterion("終了有効日時 in", values, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時NotIn(List<Date> values) {
            addCriterion("終了有効日時 not in", values, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時Between(Date value1, Date value2) {
            addCriterion("終了有効日時 between", value1, value2, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria and終了有効日時NotBetween(Date value1, Date value2) {
            addCriterion("終了有効日時 not between", value1, value2, "終了有効日時");
            return (Criteria) this;
        }

        public Criteria andファイル連携先IsNull() {
            addCriterion("ファイル連携先 is null");
            return (Criteria) this;
        }

        public Criteria andファイル連携先IsNotNull() {
            addCriterion("ファイル連携先 is not null");
            return (Criteria) this;
        }

        public Criteria andファイル連携先EqualTo(String value) {
            addCriterion("ファイル連携先 =", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先NotEqualTo(String value) {
            addCriterion("ファイル連携先 <>", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先GreaterThan(String value) {
            addCriterion("ファイル連携先 >", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先GreaterThanOrEqualTo(String value) {
            addCriterion("ファイル連携先 >=", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先LessThan(String value) {
            addCriterion("ファイル連携先 <", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先LessThanOrEqualTo(String value) {
            addCriterion("ファイル連携先 <=", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先Like(String value) {
            addCriterion("ファイル連携先 like", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先NotLike(String value) {
            addCriterion("ファイル連携先 not like", value, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先In(List<String> values) {
            addCriterion("ファイル連携先 in", values, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先NotIn(List<String> values) {
            addCriterion("ファイル連携先 not in", values, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先Between(String value1, String value2) {
            addCriterion("ファイル連携先 between", value1, value2, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携先NotBetween(String value1, String value2) {
            addCriterion("ファイル連携先 not between", value1, value2, "ファイル連携先");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidIsNull() {
            addCriterion("ファイル連携UID is null");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidIsNotNull() {
            addCriterion("ファイル連携UID is not null");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidEqualTo(String value) {
            addCriterion("ファイル連携UID =", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidNotEqualTo(String value) {
            addCriterion("ファイル連携UID <>", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidGreaterThan(String value) {
            addCriterion("ファイル連携UID >", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidGreaterThanOrEqualTo(String value) {
            addCriterion("ファイル連携UID >=", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidLessThan(String value) {
            addCriterion("ファイル連携UID <", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidLessThanOrEqualTo(String value) {
            addCriterion("ファイル連携UID <=", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidLike(String value) {
            addCriterion("ファイル連携UID like", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidNotLike(String value) {
            addCriterion("ファイル連携UID not like", value, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidIn(List<String> values) {
            addCriterion("ファイル連携UID in", values, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidNotIn(List<String> values) {
            addCriterion("ファイル連携UID not in", values, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidBetween(String value1, String value2) {
            addCriterion("ファイル連携UID between", value1, value2, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携uidNotBetween(String value1, String value2) {
            addCriterion("ファイル連携UID not between", value1, value2, "ファイル連携uid");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdIsNull() {
            addCriterion("ファイル連携PWD is null");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdIsNotNull() {
            addCriterion("ファイル連携PWD is not null");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdEqualTo(String value) {
            addCriterion("ファイル連携PWD =", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdNotEqualTo(String value) {
            addCriterion("ファイル連携PWD <>", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdGreaterThan(String value) {
            addCriterion("ファイル連携PWD >", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdGreaterThanOrEqualTo(String value) {
            addCriterion("ファイル連携PWD >=", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdLessThan(String value) {
            addCriterion("ファイル連携PWD <", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdLessThanOrEqualTo(String value) {
            addCriterion("ファイル連携PWD <=", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdLike(String value) {
            addCriterion("ファイル連携PWD like", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdNotLike(String value) {
            addCriterion("ファイル連携PWD not like", value, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdIn(List<String> values) {
            addCriterion("ファイル連携PWD in", values, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdNotIn(List<String> values) {
            addCriterion("ファイル連携PWD not in", values, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdBetween(String value1, String value2) {
            addCriterion("ファイル連携PWD between", value1, value2, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria andファイル連携pwdNotBetween(String value1, String value2) {
            addCriterion("ファイル連携PWD not between", value1, value2, "ファイル連携pwd");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNull() {
            addCriterion("登録ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNotNull() {
            addCriterion("登録ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidEqualTo(String value) {
            addCriterion("登録ユーザID =", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotEqualTo(String value) {
            addCriterion("登録ユーザID <>", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThan(String value) {
            addCriterion("登録ユーザID >", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("登録ユーザID >=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThan(String value) {
            addCriterion("登録ユーザID <", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThanOrEqualTo(String value) {
            addCriterion("登録ユーザID <=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLike(String value) {
            addCriterion("登録ユーザID like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotLike(String value) {
            addCriterion("登録ユーザID not like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIn(List<String> values) {
            addCriterion("登録ユーザID in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotIn(List<String> values) {
            addCriterion("登録ユーザID not in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidBetween(String value1, String value2) {
            addCriterion("登録ユーザID between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotBetween(String value1, String value2) {
            addCriterion("登録ユーザID not between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNull() {
            addCriterion("登録日時 is null");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNotNull() {
            addCriterion("登録日時 is not null");
            return (Criteria) this;
        }

        public Criteria and登録日時EqualTo(Date value) {
            addCriterion("登録日時 =", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotEqualTo(Date value) {
            addCriterion("登録日時 <>", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThan(Date value) {
            addCriterion("登録日時 >", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThanOrEqualTo(Date value) {
            addCriterion("登録日時 >=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThan(Date value) {
            addCriterion("登録日時 <", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThanOrEqualTo(Date value) {
            addCriterion("登録日時 <=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時In(List<Date> values) {
            addCriterion("登録日時 in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotIn(List<Date> values) {
            addCriterion("登録日時 not in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時Between(Date value1, Date value2) {
            addCriterion("登録日時 between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotBetween(Date value1, Date value2) {
            addCriterion("登録日時 not between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNull() {
            addCriterion("更新ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNotNull() {
            addCriterion("更新ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidEqualTo(String value) {
            addCriterion("更新ユーザID =", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotEqualTo(String value) {
            addCriterion("更新ユーザID <>", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThan(String value) {
            addCriterion("更新ユーザID >", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("更新ユーザID >=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThan(String value) {
            addCriterion("更新ユーザID <", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThanOrEqualTo(String value) {
            addCriterion("更新ユーザID <=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLike(String value) {
            addCriterion("更新ユーザID like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotLike(String value) {
            addCriterion("更新ユーザID not like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIn(List<String> values) {
            addCriterion("更新ユーザID in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotIn(List<String> values) {
            addCriterion("更新ユーザID not in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidBetween(String value1, String value2) {
            addCriterion("更新ユーザID between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotBetween(String value1, String value2) {
            addCriterion("更新ユーザID not between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNull() {
            addCriterion("更新日時 is null");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNotNull() {
            addCriterion("更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria and更新日時EqualTo(Date value) {
            addCriterion("更新日時 =", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotEqualTo(Date value) {
            addCriterion("更新日時 <>", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThan(Date value) {
            addCriterion("更新日時 >", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("更新日時 >=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThan(Date value) {
            addCriterion("更新日時 <", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThanOrEqualTo(Date value) {
            addCriterion("更新日時 <=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時In(List<Date> values) {
            addCriterion("更新日時 in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotIn(List<Date> values) {
            addCriterion("更新日時 not in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時Between(Date value1, Date value2) {
            addCriterion("更新日時 between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotBetween(Date value1, Date value2) {
            addCriterion("更新日時 not between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNull() {
            addCriterion("更新プログラムID is null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNotNull() {
            addCriterion("更新プログラムID is not null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidEqualTo(String value) {
            addCriterion("更新プログラムID =", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotEqualTo(String value) {
            addCriterion("更新プログラムID <>", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThan(String value) {
            addCriterion("更新プログラムID >", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThanOrEqualTo(String value) {
            addCriterion("更新プログラムID >=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThan(String value) {
            addCriterion("更新プログラムID <", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThanOrEqualTo(String value) {
            addCriterion("更新プログラムID <=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLike(String value) {
            addCriterion("更新プログラムID like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotLike(String value) {
            addCriterion("更新プログラムID not like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIn(List<String> values) {
            addCriterion("更新プログラムID in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotIn(List<String> values) {
            addCriterion("更新プログラムID not in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidBetween(String value1, String value2) {
            addCriterion("更新プログラムID between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotBetween(String value1, String value2) {
            addCriterion("更新プログラムID not between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNull() {
            addCriterion("バッチ更新日時 is null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNotNull() {
            addCriterion("バッチ更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時EqualTo(Date value) {
            addCriterion("バッチ更新日時 =", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotEqualTo(Date value) {
            addCriterion("バッチ更新日時 <>", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThan(Date value) {
            addCriterion("バッチ更新日時 >", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 >=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThan(Date value) {
            addCriterion("バッチ更新日時 <", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 <=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時In(List<Date> values) {
            addCriterion("バッチ更新日時 in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotIn(List<Date> values) {
            addCriterion("バッチ更新日時 not in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時Between(Date value1, Date value2) {
            addCriterion("バッチ更新日時 between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotBetween(Date value1, Date value2) {
            addCriterion("バッチ更新日時 not between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}