package foo.sample.db.auto.ref.model;

import java.util.Date;

public class CatvM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_CD
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_NAME
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_NAME_S
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvNameS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_KIND
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_TEL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_MAIL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CATV_DELETE_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String catvDeleteF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.CONTRACT_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String contractF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.INS_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String insUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.INS_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private Date insDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.UPD_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String updUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.UPD_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private Date updDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATV_M.PG_ID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    private String pgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_CD
     *
     * @return the value of CATV_M.CATV_CD
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvCd() {
        return catvCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_CD
     *
     * @param catvCd the value for CATV_M.CATV_CD
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvCd(String catvCd) {
        this.catvCd = catvCd == null ? null : catvCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_NAME
     *
     * @return the value of CATV_M.CATV_NAME
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvName() {
        return catvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_NAME
     *
     * @param catvName the value for CATV_M.CATV_NAME
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvName(String catvName) {
        this.catvName = catvName == null ? null : catvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_NAME_S
     *
     * @return the value of CATV_M.CATV_NAME_S
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvNameS() {
        return catvNameS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_NAME_S
     *
     * @param catvNameS the value for CATV_M.CATV_NAME_S
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvNameS(String catvNameS) {
        this.catvNameS = catvNameS == null ? null : catvNameS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_KIND
     *
     * @return the value of CATV_M.CATV_KIND
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvKind() {
        return catvKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_KIND
     *
     * @param catvKind the value for CATV_M.CATV_KIND
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvKind(String catvKind) {
        this.catvKind = catvKind == null ? null : catvKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_TEL
     *
     * @return the value of CATV_M.CATV_TEL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvTel() {
        return catvTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_TEL
     *
     * @param catvTel the value for CATV_M.CATV_TEL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvTel(String catvTel) {
        this.catvTel = catvTel == null ? null : catvTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_MAIL
     *
     * @return the value of CATV_M.CATV_MAIL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvMail() {
        return catvMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_MAIL
     *
     * @param catvMail the value for CATV_M.CATV_MAIL
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvMail(String catvMail) {
        this.catvMail = catvMail == null ? null : catvMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CATV_DELETE_F
     *
     * @return the value of CATV_M.CATV_DELETE_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getCatvDeleteF() {
        return catvDeleteF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CATV_DELETE_F
     *
     * @param catvDeleteF the value for CATV_M.CATV_DELETE_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setCatvDeleteF(String catvDeleteF) {
        this.catvDeleteF = catvDeleteF == null ? null : catvDeleteF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.CONTRACT_F
     *
     * @return the value of CATV_M.CONTRACT_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getContractF() {
        return contractF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.CONTRACT_F
     *
     * @param contractF the value for CATV_M.CONTRACT_F
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setContractF(String contractF) {
        this.contractF = contractF == null ? null : contractF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.INS_UID
     *
     * @return the value of CATV_M.INS_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getInsUid() {
        return insUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.INS_UID
     *
     * @param insUid the value for CATV_M.INS_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setInsUid(String insUid) {
        this.insUid = insUid == null ? null : insUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.INS_DATE
     *
     * @return the value of CATV_M.INS_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.INS_DATE
     *
     * @param insDate the value for CATV_M.INS_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.UPD_UID
     *
     * @return the value of CATV_M.UPD_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getUpdUid() {
        return updUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.UPD_UID
     *
     * @param updUid the value for CATV_M.UPD_UID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setUpdUid(String updUid) {
        this.updUid = updUid == null ? null : updUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.UPD_DATE
     *
     * @return the value of CATV_M.UPD_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.UPD_DATE
     *
     * @param updDate the value for CATV_M.UPD_DATE
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATV_M.PG_ID
     *
     * @return the value of CATV_M.PG_ID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public String getPgId() {
        return pgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATV_M.PG_ID
     *
     * @param pgId the value for CATV_M.PG_ID
     *
     * @mbg.generated Thu Jan 10 17:02:42 JST 2019
     */
    public void setPgId(String pgId) {
        this.pgId = pgId == null ? null : pgId.trim();
    }
}