package foo.sample.db.auto.ref.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class 商品区分マスタExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public 商品区分マスタExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpIdIsNull() {
            addCriterion("SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(String value) {
            addCriterion("SP_ID =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(String value) {
            addCriterion("SP_ID <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(String value) {
            addCriterion("SP_ID >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ID >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(String value) {
            addCriterion("SP_ID <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ID <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLike(String value) {
            addCriterion("SP_ID like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotLike(String value) {
            addCriterion("SP_ID not like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<String> values) {
            addCriterion("SP_ID in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<String> values) {
            addCriterion("SP_ID not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(String value1, String value2) {
            addCriterion("SP_ID between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(String value1, String value2) {
            addCriterion("SP_ID not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria and商品区分CIsNull() {
            addCriterion("商品区分_C is null");
            return (Criteria) this;
        }

        public Criteria and商品区分CIsNotNull() {
            addCriterion("商品区分_C is not null");
            return (Criteria) this;
        }

        public Criteria and商品区分CEqualTo(String value) {
            addCriterion("商品区分_C =", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotEqualTo(String value) {
            addCriterion("商品区分_C <>", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CGreaterThan(String value) {
            addCriterion("商品区分_C >", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CGreaterThanOrEqualTo(String value) {
            addCriterion("商品区分_C >=", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLessThan(String value) {
            addCriterion("商品区分_C <", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLessThanOrEqualTo(String value) {
            addCriterion("商品区分_C <=", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLike(String value) {
            addCriterion("商品区分_C like", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotLike(String value) {
            addCriterion("商品区分_C not like", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CIn(List<String> values) {
            addCriterion("商品区分_C in", values, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotIn(List<String> values) {
            addCriterion("商品区分_C not in", values, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CBetween(String value1, String value2) {
            addCriterion("商品区分_C between", value1, value2, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotBetween(String value1, String value2) {
            addCriterion("商品区分_C not between", value1, value2, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分名称IsNull() {
            addCriterion("商品区分名称 is null");
            return (Criteria) this;
        }

        public Criteria and商品区分名称IsNotNull() {
            addCriterion("商品区分名称 is not null");
            return (Criteria) this;
        }

        public Criteria and商品区分名称EqualTo(String value) {
            addCriterion("商品区分名称 =", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称NotEqualTo(String value) {
            addCriterion("商品区分名称 <>", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称GreaterThan(String value) {
            addCriterion("商品区分名称 >", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称GreaterThanOrEqualTo(String value) {
            addCriterion("商品区分名称 >=", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称LessThan(String value) {
            addCriterion("商品区分名称 <", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称LessThanOrEqualTo(String value) {
            addCriterion("商品区分名称 <=", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称Like(String value) {
            addCriterion("商品区分名称 like", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称NotLike(String value) {
            addCriterion("商品区分名称 not like", value, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称In(List<String> values) {
            addCriterion("商品区分名称 in", values, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称NotIn(List<String> values) {
            addCriterion("商品区分名称 not in", values, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称Between(String value1, String value2) {
            addCriterion("商品区分名称 between", value1, value2, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and商品区分名称NotBetween(String value1, String value2) {
            addCriterion("商品区分名称 not between", value1, value2, "商品区分名称");
            return (Criteria) this;
        }

        public Criteria and基本商品FIsNull() {
            addCriterion("基本商品_F is null");
            return (Criteria) this;
        }

        public Criteria and基本商品FIsNotNull() {
            addCriterion("基本商品_F is not null");
            return (Criteria) this;
        }

        public Criteria and基本商品FEqualTo(String value) {
            addCriterion("基本商品_F =", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotEqualTo(String value) {
            addCriterion("基本商品_F <>", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FGreaterThan(String value) {
            addCriterion("基本商品_F >", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FGreaterThanOrEqualTo(String value) {
            addCriterion("基本商品_F >=", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLessThan(String value) {
            addCriterion("基本商品_F <", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLessThanOrEqualTo(String value) {
            addCriterion("基本商品_F <=", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLike(String value) {
            addCriterion("基本商品_F like", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotLike(String value) {
            addCriterion("基本商品_F not like", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FIn(List<String> values) {
            addCriterion("基本商品_F in", values, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotIn(List<String> values) {
            addCriterion("基本商品_F not in", values, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FBetween(String value1, String value2) {
            addCriterion("基本商品_F between", value1, value2, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotBetween(String value1, String value2) {
            addCriterion("基本商品_F not between", value1, value2, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FIsNull() {
            addCriterion("画面設定基本商品_F is null");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FIsNotNull() {
            addCriterion("画面設定基本商品_F is not null");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FEqualTo(String value) {
            addCriterion("画面設定基本商品_F =", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FNotEqualTo(String value) {
            addCriterion("画面設定基本商品_F <>", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FGreaterThan(String value) {
            addCriterion("画面設定基本商品_F >", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FGreaterThanOrEqualTo(String value) {
            addCriterion("画面設定基本商品_F >=", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FLessThan(String value) {
            addCriterion("画面設定基本商品_F <", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FLessThanOrEqualTo(String value) {
            addCriterion("画面設定基本商品_F <=", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FLike(String value) {
            addCriterion("画面設定基本商品_F like", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FNotLike(String value) {
            addCriterion("画面設定基本商品_F not like", value, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FIn(List<String> values) {
            addCriterion("画面設定基本商品_F in", values, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FNotIn(List<String> values) {
            addCriterion("画面設定基本商品_F not in", values, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FBetween(String value1, String value2) {
            addCriterion("画面設定基本商品_F between", value1, value2, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定基本商品FNotBetween(String value1, String value2) {
            addCriterion("画面設定基本商品_F not between", value1, value2, "画面設定基本商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FIsNull() {
            addCriterion("画面設定共通商品_F is null");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FIsNotNull() {
            addCriterion("画面設定共通商品_F is not null");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FEqualTo(String value) {
            addCriterion("画面設定共通商品_F =", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FNotEqualTo(String value) {
            addCriterion("画面設定共通商品_F <>", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FGreaterThan(String value) {
            addCriterion("画面設定共通商品_F >", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FGreaterThanOrEqualTo(String value) {
            addCriterion("画面設定共通商品_F >=", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FLessThan(String value) {
            addCriterion("画面設定共通商品_F <", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FLessThanOrEqualTo(String value) {
            addCriterion("画面設定共通商品_F <=", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FLike(String value) {
            addCriterion("画面設定共通商品_F like", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FNotLike(String value) {
            addCriterion("画面設定共通商品_F not like", value, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FIn(List<String> values) {
            addCriterion("画面設定共通商品_F in", values, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FNotIn(List<String> values) {
            addCriterion("画面設定共通商品_F not in", values, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FBetween(String value1, String value2) {
            addCriterion("画面設定共通商品_F between", value1, value2, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定共通商品FNotBetween(String value1, String value2) {
            addCriterion("画面設定共通商品_F not between", value1, value2, "画面設定共通商品F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FIsNull() {
            addCriterion("画面設定金額_F is null");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FIsNotNull() {
            addCriterion("画面設定金額_F is not null");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FEqualTo(String value) {
            addCriterion("画面設定金額_F =", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FNotEqualTo(String value) {
            addCriterion("画面設定金額_F <>", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FGreaterThan(String value) {
            addCriterion("画面設定金額_F >", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FGreaterThanOrEqualTo(String value) {
            addCriterion("画面設定金額_F >=", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FLessThan(String value) {
            addCriterion("画面設定金額_F <", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FLessThanOrEqualTo(String value) {
            addCriterion("画面設定金額_F <=", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FLike(String value) {
            addCriterion("画面設定金額_F like", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FNotLike(String value) {
            addCriterion("画面設定金額_F not like", value, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FIn(List<String> values) {
            addCriterion("画面設定金額_F in", values, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FNotIn(List<String> values) {
            addCriterion("画面設定金額_F not in", values, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FBetween(String value1, String value2) {
            addCriterion("画面設定金額_F between", value1, value2, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定金額FNotBetween(String value1, String value2) {
            addCriterion("画面設定金額_F not between", value1, value2, "画面設定金額F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FIsNull() {
            addCriterion("画面設定容量_F is null");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FIsNotNull() {
            addCriterion("画面設定容量_F is not null");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FEqualTo(String value) {
            addCriterion("画面設定容量_F =", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FNotEqualTo(String value) {
            addCriterion("画面設定容量_F <>", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FGreaterThan(String value) {
            addCriterion("画面設定容量_F >", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FGreaterThanOrEqualTo(String value) {
            addCriterion("画面設定容量_F >=", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FLessThan(String value) {
            addCriterion("画面設定容量_F <", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FLessThanOrEqualTo(String value) {
            addCriterion("画面設定容量_F <=", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FLike(String value) {
            addCriterion("画面設定容量_F like", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FNotLike(String value) {
            addCriterion("画面設定容量_F not like", value, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FIn(List<String> values) {
            addCriterion("画面設定容量_F in", values, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FNotIn(List<String> values) {
            addCriterion("画面設定容量_F not in", values, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FBetween(String value1, String value2) {
            addCriterion("画面設定容量_F between", value1, value2, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and画面設定容量FNotBetween(String value1, String value2) {
            addCriterion("画面設定容量_F not between", value1, value2, "画面設定容量F");
            return (Criteria) this;
        }

        public Criteria and自動終了月数IsNull() {
            addCriterion("自動終了月数 is null");
            return (Criteria) this;
        }

        public Criteria and自動終了月数IsNotNull() {
            addCriterion("自動終了月数 is not null");
            return (Criteria) this;
        }

        public Criteria and自動終了月数EqualTo(Integer value) {
            addCriterion("自動終了月数 =", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数NotEqualTo(Integer value) {
            addCriterion("自動終了月数 <>", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数GreaterThan(Integer value) {
            addCriterion("自動終了月数 >", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数GreaterThanOrEqualTo(Integer value) {
            addCriterion("自動終了月数 >=", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数LessThan(Integer value) {
            addCriterion("自動終了月数 <", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数LessThanOrEqualTo(Integer value) {
            addCriterion("自動終了月数 <=", value, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数In(List<Integer> values) {
            addCriterion("自動終了月数 in", values, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数NotIn(List<Integer> values) {
            addCriterion("自動終了月数 not in", values, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数Between(Integer value1, Integer value2) {
            addCriterion("自動終了月数 between", value1, value2, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月数NotBetween(Integer value1, Integer value2) {
            addCriterion("自動終了月数 not between", value1, value2, "自動終了月数");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FIsNull() {
            addCriterion("自動終了月末_F is null");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FIsNotNull() {
            addCriterion("自動終了月末_F is not null");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FEqualTo(String value) {
            addCriterion("自動終了月末_F =", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FNotEqualTo(String value) {
            addCriterion("自動終了月末_F <>", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FGreaterThan(String value) {
            addCriterion("自動終了月末_F >", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FGreaterThanOrEqualTo(String value) {
            addCriterion("自動終了月末_F >=", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FLessThan(String value) {
            addCriterion("自動終了月末_F <", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FLessThanOrEqualTo(String value) {
            addCriterion("自動終了月末_F <=", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FLike(String value) {
            addCriterion("自動終了月末_F like", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FNotLike(String value) {
            addCriterion("自動終了月末_F not like", value, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FIn(List<String> values) {
            addCriterion("自動終了月末_F in", values, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FNotIn(List<String> values) {
            addCriterion("自動終了月末_F not in", values, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FBetween(String value1, String value2) {
            addCriterion("自動終了月末_F between", value1, value2, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了月末FNotBetween(String value1, String value2) {
            addCriterion("自動終了月末_F not between", value1, value2, "自動終了月末F");
            return (Criteria) this;
        }

        public Criteria and自動終了日数IsNull() {
            addCriterion("自動終了日数 is null");
            return (Criteria) this;
        }

        public Criteria and自動終了日数IsNotNull() {
            addCriterion("自動終了日数 is not null");
            return (Criteria) this;
        }

        public Criteria and自動終了日数EqualTo(Integer value) {
            addCriterion("自動終了日数 =", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数NotEqualTo(Integer value) {
            addCriterion("自動終了日数 <>", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数GreaterThan(Integer value) {
            addCriterion("自動終了日数 >", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数GreaterThanOrEqualTo(Integer value) {
            addCriterion("自動終了日数 >=", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数LessThan(Integer value) {
            addCriterion("自動終了日数 <", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数LessThanOrEqualTo(Integer value) {
            addCriterion("自動終了日数 <=", value, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数In(List<Integer> values) {
            addCriterion("自動終了日数 in", values, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数NotIn(List<Integer> values) {
            addCriterion("自動終了日数 not in", values, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数Between(Integer value1, Integer value2) {
            addCriterion("自動終了日数 between", value1, value2, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and自動終了日数NotBetween(Integer value1, Integer value2) {
            addCriterion("自動終了日数 not between", value1, value2, "自動終了日数");
            return (Criteria) this;
        }

        public Criteria and固定FIsNull() {
            addCriterion("固定_F is null");
            return (Criteria) this;
        }

        public Criteria and固定FIsNotNull() {
            addCriterion("固定_F is not null");
            return (Criteria) this;
        }

        public Criteria and固定FEqualTo(String value) {
            addCriterion("固定_F =", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FNotEqualTo(String value) {
            addCriterion("固定_F <>", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FGreaterThan(String value) {
            addCriterion("固定_F >", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FGreaterThanOrEqualTo(String value) {
            addCriterion("固定_F >=", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FLessThan(String value) {
            addCriterion("固定_F <", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FLessThanOrEqualTo(String value) {
            addCriterion("固定_F <=", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FLike(String value) {
            addCriterion("固定_F like", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FNotLike(String value) {
            addCriterion("固定_F not like", value, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FIn(List<String> values) {
            addCriterion("固定_F in", values, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FNotIn(List<String> values) {
            addCriterion("固定_F not in", values, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FBetween(String value1, String value2) {
            addCriterion("固定_F between", value1, value2, "固定F");
            return (Criteria) this;
        }

        public Criteria and固定FNotBetween(String value1, String value2) {
            addCriterion("固定_F not between", value1, value2, "固定F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FIsNull() {
            addCriterion("ファイル出力_F is null");
            return (Criteria) this;
        }

        public Criteria andファイル出力FIsNotNull() {
            addCriterion("ファイル出力_F is not null");
            return (Criteria) this;
        }

        public Criteria andファイル出力FEqualTo(String value) {
            addCriterion("ファイル出力_F =", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FNotEqualTo(String value) {
            addCriterion("ファイル出力_F <>", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FGreaterThan(String value) {
            addCriterion("ファイル出力_F >", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FGreaterThanOrEqualTo(String value) {
            addCriterion("ファイル出力_F >=", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FLessThan(String value) {
            addCriterion("ファイル出力_F <", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FLessThanOrEqualTo(String value) {
            addCriterion("ファイル出力_F <=", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FLike(String value) {
            addCriterion("ファイル出力_F like", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FNotLike(String value) {
            addCriterion("ファイル出力_F not like", value, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FIn(List<String> values) {
            addCriterion("ファイル出力_F in", values, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FNotIn(List<String> values) {
            addCriterion("ファイル出力_F not in", values, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FBetween(String value1, String value2) {
            addCriterion("ファイル出力_F between", value1, value2, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria andファイル出力FNotBetween(String value1, String value2) {
            addCriterion("ファイル出力_F not between", value1, value2, "ファイル出力F");
            return (Criteria) this;
        }

        public Criteria and月額課金FIsNull() {
            addCriterion("月額課金_F is null");
            return (Criteria) this;
        }

        public Criteria and月額課金FIsNotNull() {
            addCriterion("月額課金_F is not null");
            return (Criteria) this;
        }

        public Criteria and月額課金FEqualTo(String value) {
            addCriterion("月額課金_F =", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FNotEqualTo(String value) {
            addCriterion("月額課金_F <>", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FGreaterThan(String value) {
            addCriterion("月額課金_F >", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FGreaterThanOrEqualTo(String value) {
            addCriterion("月額課金_F >=", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FLessThan(String value) {
            addCriterion("月額課金_F <", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FLessThanOrEqualTo(String value) {
            addCriterion("月額課金_F <=", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FLike(String value) {
            addCriterion("月額課金_F like", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FNotLike(String value) {
            addCriterion("月額課金_F not like", value, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FIn(List<String> values) {
            addCriterion("月額課金_F in", values, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FNotIn(List<String> values) {
            addCriterion("月額課金_F not in", values, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FBetween(String value1, String value2) {
            addCriterion("月額課金_F between", value1, value2, "月額課金F");
            return (Criteria) this;
        }

        public Criteria and月額課金FNotBetween(String value1, String value2) {
            addCriterion("月額課金_F not between", value1, value2, "月額課金F");
            return (Criteria) this;
        }

        public Criteria andEu出力FIsNull() {
            addCriterion("EU出力_F is null");
            return (Criteria) this;
        }

        public Criteria andEu出力FIsNotNull() {
            addCriterion("EU出力_F is not null");
            return (Criteria) this;
        }

        public Criteria andEu出力FEqualTo(String value) {
            addCriterion("EU出力_F =", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FNotEqualTo(String value) {
            addCriterion("EU出力_F <>", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FGreaterThan(String value) {
            addCriterion("EU出力_F >", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FGreaterThanOrEqualTo(String value) {
            addCriterion("EU出力_F >=", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FLessThan(String value) {
            addCriterion("EU出力_F <", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FLessThanOrEqualTo(String value) {
            addCriterion("EU出力_F <=", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FLike(String value) {
            addCriterion("EU出力_F like", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FNotLike(String value) {
            addCriterion("EU出力_F not like", value, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FIn(List<String> values) {
            addCriterion("EU出力_F in", values, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FNotIn(List<String> values) {
            addCriterion("EU出力_F not in", values, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FBetween(String value1, String value2) {
            addCriterion("EU出力_F between", value1, value2, "eu出力F");
            return (Criteria) this;
        }

        public Criteria andEu出力FNotBetween(String value1, String value2) {
            addCriterion("EU出力_F not between", value1, value2, "eu出力F");
            return (Criteria) this;
        }

        public Criteria and税区分IsNull() {
            addCriterion("税区分 is null");
            return (Criteria) this;
        }

        public Criteria and税区分IsNotNull() {
            addCriterion("税区分 is not null");
            return (Criteria) this;
        }

        public Criteria and税区分EqualTo(String value) {
            addCriterion("税区分 =", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分NotEqualTo(String value) {
            addCriterion("税区分 <>", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分GreaterThan(String value) {
            addCriterion("税区分 >", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分GreaterThanOrEqualTo(String value) {
            addCriterion("税区分 >=", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分LessThan(String value) {
            addCriterion("税区分 <", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分LessThanOrEqualTo(String value) {
            addCriterion("税区分 <=", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分Like(String value) {
            addCriterion("税区分 like", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分NotLike(String value) {
            addCriterion("税区分 not like", value, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分In(List<String> values) {
            addCriterion("税区分 in", values, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分NotIn(List<String> values) {
            addCriterion("税区分 not in", values, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分Between(String value1, String value2) {
            addCriterion("税区分 between", value1, value2, "税区分");
            return (Criteria) this;
        }

        public Criteria and税区分NotBetween(String value1, String value2) {
            addCriterion("税区分 not between", value1, value2, "税区分");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CIsNull() {
            addCriterion("API商品区分_C is null");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CIsNotNull() {
            addCriterion("API商品区分_C is not null");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CEqualTo(String value) {
            addCriterion("API商品区分_C =", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CNotEqualTo(String value) {
            addCriterion("API商品区分_C <>", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CGreaterThan(String value) {
            addCriterion("API商品区分_C >", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CGreaterThanOrEqualTo(String value) {
            addCriterion("API商品区分_C >=", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CLessThan(String value) {
            addCriterion("API商品区分_C <", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CLessThanOrEqualTo(String value) {
            addCriterion("API商品区分_C <=", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CLike(String value) {
            addCriterion("API商品区分_C like", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CNotLike(String value) {
            addCriterion("API商品区分_C not like", value, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CIn(List<String> values) {
            addCriterion("API商品区分_C in", values, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CNotIn(List<String> values) {
            addCriterion("API商品区分_C not in", values, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CBetween(String value1, String value2) {
            addCriterion("API商品区分_C between", value1, value2, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria andApi商品区分CNotBetween(String value1, String value2) {
            addCriterion("API商品区分_C not between", value1, value2, "api商品区分C");
            return (Criteria) this;
        }

        public Criteria and定額時間IsNull() {
            addCriterion("定額時間 is null");
            return (Criteria) this;
        }

        public Criteria and定額時間IsNotNull() {
            addCriterion("定額時間 is not null");
            return (Criteria) this;
        }

        public Criteria and定額時間EqualTo(Integer value) {
            addCriterion("定額時間 =", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間NotEqualTo(Integer value) {
            addCriterion("定額時間 <>", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間GreaterThan(Integer value) {
            addCriterion("定額時間 >", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間GreaterThanOrEqualTo(Integer value) {
            addCriterion("定額時間 >=", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間LessThan(Integer value) {
            addCriterion("定額時間 <", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間LessThanOrEqualTo(Integer value) {
            addCriterion("定額時間 <=", value, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間In(List<Integer> values) {
            addCriterion("定額時間 in", values, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間NotIn(List<Integer> values) {
            addCriterion("定額時間 not in", values, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間Between(Integer value1, Integer value2) {
            addCriterion("定額時間 between", value1, value2, "定額時間");
            return (Criteria) this;
        }

        public Criteria and定額時間NotBetween(Integer value1, Integer value2) {
            addCriterion("定額時間 not between", value1, value2, "定額時間");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順IsNull() {
            addCriterion("通話料金表示順 is null");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順IsNotNull() {
            addCriterion("通話料金表示順 is not null");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順EqualTo(Integer value) {
            addCriterion("通話料金表示順 =", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順NotEqualTo(Integer value) {
            addCriterion("通話料金表示順 <>", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順GreaterThan(Integer value) {
            addCriterion("通話料金表示順 >", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順GreaterThanOrEqualTo(Integer value) {
            addCriterion("通話料金表示順 >=", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順LessThan(Integer value) {
            addCriterion("通話料金表示順 <", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順LessThanOrEqualTo(Integer value) {
            addCriterion("通話料金表示順 <=", value, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順In(List<Integer> values) {
            addCriterion("通話料金表示順 in", values, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順NotIn(List<Integer> values) {
            addCriterion("通話料金表示順 not in", values, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順Between(Integer value1, Integer value2) {
            addCriterion("通話料金表示順 between", value1, value2, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and通話料金表示順NotBetween(Integer value1, Integer value2) {
            addCriterion("通話料金表示順 not between", value1, value2, "通話料金表示順");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNull() {
            addCriterion("登録ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNotNull() {
            addCriterion("登録ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidEqualTo(String value) {
            addCriterion("登録ユーザID =", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotEqualTo(String value) {
            addCriterion("登録ユーザID <>", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThan(String value) {
            addCriterion("登録ユーザID >", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("登録ユーザID >=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThan(String value) {
            addCriterion("登録ユーザID <", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThanOrEqualTo(String value) {
            addCriterion("登録ユーザID <=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLike(String value) {
            addCriterion("登録ユーザID like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotLike(String value) {
            addCriterion("登録ユーザID not like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIn(List<String> values) {
            addCriterion("登録ユーザID in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotIn(List<String> values) {
            addCriterion("登録ユーザID not in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidBetween(String value1, String value2) {
            addCriterion("登録ユーザID between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotBetween(String value1, String value2) {
            addCriterion("登録ユーザID not between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNull() {
            addCriterion("登録日時 is null");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNotNull() {
            addCriterion("登録日時 is not null");
            return (Criteria) this;
        }

        public Criteria and登録日時EqualTo(Date value) {
            addCriterion("登録日時 =", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotEqualTo(Date value) {
            addCriterion("登録日時 <>", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThan(Date value) {
            addCriterion("登録日時 >", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThanOrEqualTo(Date value) {
            addCriterion("登録日時 >=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThan(Date value) {
            addCriterion("登録日時 <", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThanOrEqualTo(Date value) {
            addCriterion("登録日時 <=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時In(List<Date> values) {
            addCriterion("登録日時 in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotIn(List<Date> values) {
            addCriterion("登録日時 not in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時Between(Date value1, Date value2) {
            addCriterion("登録日時 between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotBetween(Date value1, Date value2) {
            addCriterion("登録日時 not between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNull() {
            addCriterion("更新ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNotNull() {
            addCriterion("更新ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidEqualTo(String value) {
            addCriterion("更新ユーザID =", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotEqualTo(String value) {
            addCriterion("更新ユーザID <>", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThan(String value) {
            addCriterion("更新ユーザID >", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("更新ユーザID >=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThan(String value) {
            addCriterion("更新ユーザID <", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThanOrEqualTo(String value) {
            addCriterion("更新ユーザID <=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLike(String value) {
            addCriterion("更新ユーザID like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotLike(String value) {
            addCriterion("更新ユーザID not like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIn(List<String> values) {
            addCriterion("更新ユーザID in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotIn(List<String> values) {
            addCriterion("更新ユーザID not in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidBetween(String value1, String value2) {
            addCriterion("更新ユーザID between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotBetween(String value1, String value2) {
            addCriterion("更新ユーザID not between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNull() {
            addCriterion("更新日時 is null");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNotNull() {
            addCriterion("更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria and更新日時EqualTo(Date value) {
            addCriterion("更新日時 =", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotEqualTo(Date value) {
            addCriterion("更新日時 <>", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThan(Date value) {
            addCriterion("更新日時 >", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("更新日時 >=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThan(Date value) {
            addCriterion("更新日時 <", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThanOrEqualTo(Date value) {
            addCriterion("更新日時 <=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時In(List<Date> values) {
            addCriterion("更新日時 in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotIn(List<Date> values) {
            addCriterion("更新日時 not in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時Between(Date value1, Date value2) {
            addCriterion("更新日時 between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotBetween(Date value1, Date value2) {
            addCriterion("更新日時 not between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNull() {
            addCriterion("更新プログラムID is null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNotNull() {
            addCriterion("更新プログラムID is not null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidEqualTo(String value) {
            addCriterion("更新プログラムID =", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotEqualTo(String value) {
            addCriterion("更新プログラムID <>", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThan(String value) {
            addCriterion("更新プログラムID >", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThanOrEqualTo(String value) {
            addCriterion("更新プログラムID >=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThan(String value) {
            addCriterion("更新プログラムID <", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThanOrEqualTo(String value) {
            addCriterion("更新プログラムID <=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLike(String value) {
            addCriterion("更新プログラムID like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotLike(String value) {
            addCriterion("更新プログラムID not like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIn(List<String> values) {
            addCriterion("更新プログラムID in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotIn(List<String> values) {
            addCriterion("更新プログラムID not in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidBetween(String value1, String value2) {
            addCriterion("更新プログラムID between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotBetween(String value1, String value2) {
            addCriterion("更新プログラムID not between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNull() {
            addCriterion("バッチ更新日時 is null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNotNull() {
            addCriterion("バッチ更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時EqualTo(Date value) {
            addCriterion("バッチ更新日時 =", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotEqualTo(Date value) {
            addCriterion("バッチ更新日時 <>", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThan(Date value) {
            addCriterion("バッチ更新日時 >", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 >=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThan(Date value) {
            addCriterion("バッチ更新日時 <", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 <=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時In(List<Date> values) {
            addCriterion("バッチ更新日時 in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotIn(List<Date> values) {
            addCriterion("バッチ更新日時 not in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時Between(Date value1, Date value2) {
            addCriterion("バッチ更新日時 between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotBetween(Date value1, Date value2) {
            addCriterion("バッチ更新日時 not between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}