package foo.sample.db.auto.ref.model;

import java.util.Date;

public class 商品マスタ extends 商品マスタKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.商品区分_C
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 商品区分C;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.商品名称
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 商品名称;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.税抜金額
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private Long 税抜金額;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.容量
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private Long 容量;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.基本商品_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 基本商品F;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.非表示_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 非表示F;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.当月有効_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 当月有効F;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.グループCD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String グループcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.登録ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 登録ユーザid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.登録日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private Date 登録日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.更新ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 更新ユーザid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private Date 更新日時;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.更新プログラムID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private String 更新プログラムid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 商品マスタ.バッチ更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    private Date バッチ更新日時;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.商品区分_C
     *
     * @return the value of 商品マスタ.商品区分_C
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get商品区分C() {
        return 商品区分C;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.商品区分_C
     *
     * @param 商品区分C the value for 商品マスタ.商品区分_C
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set商品区分C(String 商品区分C) {
        this.商品区分C = 商品区分C == null ? null : 商品区分C.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.商品名称
     *
     * @return the value of 商品マスタ.商品名称
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get商品名称() {
        return 商品名称;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.商品名称
     *
     * @param 商品名称 the value for 商品マスタ.商品名称
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set商品名称(String 商品名称) {
        this.商品名称 = 商品名称 == null ? null : 商品名称.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.税抜金額
     *
     * @return the value of 商品マスタ.税抜金額
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Long get税抜金額() {
        return 税抜金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.税抜金額
     *
     * @param 税抜金額 the value for 商品マスタ.税抜金額
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set税抜金額(Long 税抜金額) {
        this.税抜金額 = 税抜金額;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.容量
     *
     * @return the value of 商品マスタ.容量
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Long get容量() {
        return 容量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.容量
     *
     * @param 容量 the value for 商品マスタ.容量
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set容量(Long 容量) {
        this.容量 = 容量;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.基本商品_F
     *
     * @return the value of 商品マスタ.基本商品_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get基本商品F() {
        return 基本商品F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.基本商品_F
     *
     * @param 基本商品F the value for 商品マスタ.基本商品_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set基本商品F(String 基本商品F) {
        this.基本商品F = 基本商品F == null ? null : 基本商品F.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.非表示_F
     *
     * @return the value of 商品マスタ.非表示_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get非表示F() {
        return 非表示F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.非表示_F
     *
     * @param 非表示F the value for 商品マスタ.非表示_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set非表示F(String 非表示F) {
        this.非表示F = 非表示F == null ? null : 非表示F.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.当月有効_F
     *
     * @return the value of 商品マスタ.当月有効_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get当月有効F() {
        return 当月有効F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.当月有効_F
     *
     * @param 当月有効F the value for 商品マスタ.当月有効_F
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set当月有効F(String 当月有効F) {
        this.当月有効F = 当月有効F == null ? null : 当月有効F.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.グループCD
     *
     * @return the value of 商品マスタ.グループCD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getグループcd() {
        return グループcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.グループCD
     *
     * @param グループcd the value for 商品マスタ.グループCD
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setグループcd(String グループcd) {
        this.グループcd = グループcd == null ? null : グループcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.登録ユーザID
     *
     * @return the value of 商品マスタ.登録ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get登録ユーザid() {
        return 登録ユーザid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.登録ユーザID
     *
     * @param 登録ユーザid the value for 商品マスタ.登録ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set登録ユーザid(String 登録ユーザid) {
        this.登録ユーザid = 登録ユーザid == null ? null : 登録ユーザid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.登録日時
     *
     * @return the value of 商品マスタ.登録日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Date get登録日時() {
        return 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.登録日時
     *
     * @param 登録日時 the value for 商品マスタ.登録日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set登録日時(Date 登録日時) {
        this.登録日時 = 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.更新ユーザID
     *
     * @return the value of 商品マスタ.更新ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get更新ユーザid() {
        return 更新ユーザid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.更新ユーザID
     *
     * @param 更新ユーザid the value for 商品マスタ.更新ユーザID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set更新ユーザid(String 更新ユーザid) {
        this.更新ユーザid = 更新ユーザid == null ? null : 更新ユーザid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.更新日時
     *
     * @return the value of 商品マスタ.更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Date get更新日時() {
        return 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.更新日時
     *
     * @param 更新日時 the value for 商品マスタ.更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set更新日時(Date 更新日時) {
        this.更新日時 = 更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.更新プログラムID
     *
     * @return the value of 商品マスタ.更新プログラムID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String get更新プログラムid() {
        return 更新プログラムid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.更新プログラムID
     *
     * @param 更新プログラムid the value for 商品マスタ.更新プログラムID
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void set更新プログラムid(String 更新プログラムid) {
        this.更新プログラムid = 更新プログラムid == null ? null : 更新プログラムid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 商品マスタ.バッチ更新日時
     *
     * @return the value of 商品マスタ.バッチ更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Date getバッチ更新日時() {
        return バッチ更新日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 商品マスタ.バッチ更新日時
     *
     * @param バッチ更新日時 the value for 商品マスタ.バッチ更新日時
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setバッチ更新日時(Date バッチ更新日時) {
        this.バッチ更新日時 = バッチ更新日時;
    }
}