package foo.sample.db.auto.ref.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class 商品マスタExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public 商品マスタExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCatvCdIsNull() {
            addCriterion("CATV_CD is null");
            return (Criteria) this;
        }

        public Criteria andCatvCdIsNotNull() {
            addCriterion("CATV_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCatvCdEqualTo(String value) {
            addCriterion("CATV_CD =", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotEqualTo(String value) {
            addCriterion("CATV_CD <>", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdGreaterThan(String value) {
            addCriterion("CATV_CD >", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdGreaterThanOrEqualTo(String value) {
            addCriterion("CATV_CD >=", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLessThan(String value) {
            addCriterion("CATV_CD <", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLessThanOrEqualTo(String value) {
            addCriterion("CATV_CD <=", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdLike(String value) {
            addCriterion("CATV_CD like", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotLike(String value) {
            addCriterion("CATV_CD not like", value, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdIn(List<String> values) {
            addCriterion("CATV_CD in", values, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotIn(List<String> values) {
            addCriterion("CATV_CD not in", values, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdBetween(String value1, String value2) {
            addCriterion("CATV_CD between", value1, value2, "catvCd");
            return (Criteria) this;
        }

        public Criteria andCatvCdNotBetween(String value1, String value2) {
            addCriterion("CATV_CD not between", value1, value2, "catvCd");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNull() {
            addCriterion("SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(String value) {
            addCriterion("SP_ID =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(String value) {
            addCriterion("SP_ID <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(String value) {
            addCriterion("SP_ID >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ID >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(String value) {
            addCriterion("SP_ID <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ID <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLike(String value) {
            addCriterion("SP_ID like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotLike(String value) {
            addCriterion("SP_ID not like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<String> values) {
            addCriterion("SP_ID in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<String> values) {
            addCriterion("SP_ID not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(String value1, String value2) {
            addCriterion("SP_ID between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(String value1, String value2) {
            addCriterion("SP_ID not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria and商品CIsNull() {
            addCriterion("商品_C is null");
            return (Criteria) this;
        }

        public Criteria and商品CIsNotNull() {
            addCriterion("商品_C is not null");
            return (Criteria) this;
        }

        public Criteria and商品CEqualTo(String value) {
            addCriterion("商品_C =", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CNotEqualTo(String value) {
            addCriterion("商品_C <>", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CGreaterThan(String value) {
            addCriterion("商品_C >", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CGreaterThanOrEqualTo(String value) {
            addCriterion("商品_C >=", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CLessThan(String value) {
            addCriterion("商品_C <", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CLessThanOrEqualTo(String value) {
            addCriterion("商品_C <=", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CLike(String value) {
            addCriterion("商品_C like", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CNotLike(String value) {
            addCriterion("商品_C not like", value, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CIn(List<String> values) {
            addCriterion("商品_C in", values, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CNotIn(List<String> values) {
            addCriterion("商品_C not in", values, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CBetween(String value1, String value2) {
            addCriterion("商品_C between", value1, value2, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品CNotBetween(String value1, String value2) {
            addCriterion("商品_C not between", value1, value2, "商品C");
            return (Criteria) this;
        }

        public Criteria and商品区分CIsNull() {
            addCriterion("商品区分_C is null");
            return (Criteria) this;
        }

        public Criteria and商品区分CIsNotNull() {
            addCriterion("商品区分_C is not null");
            return (Criteria) this;
        }

        public Criteria and商品区分CEqualTo(String value) {
            addCriterion("商品区分_C =", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotEqualTo(String value) {
            addCriterion("商品区分_C <>", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CGreaterThan(String value) {
            addCriterion("商品区分_C >", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CGreaterThanOrEqualTo(String value) {
            addCriterion("商品区分_C >=", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLessThan(String value) {
            addCriterion("商品区分_C <", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLessThanOrEqualTo(String value) {
            addCriterion("商品区分_C <=", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CLike(String value) {
            addCriterion("商品区分_C like", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotLike(String value) {
            addCriterion("商品区分_C not like", value, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CIn(List<String> values) {
            addCriterion("商品区分_C in", values, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotIn(List<String> values) {
            addCriterion("商品区分_C not in", values, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CBetween(String value1, String value2) {
            addCriterion("商品区分_C between", value1, value2, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品区分CNotBetween(String value1, String value2) {
            addCriterion("商品区分_C not between", value1, value2, "商品区分C");
            return (Criteria) this;
        }

        public Criteria and商品名称IsNull() {
            addCriterion("商品名称 is null");
            return (Criteria) this;
        }

        public Criteria and商品名称IsNotNull() {
            addCriterion("商品名称 is not null");
            return (Criteria) this;
        }

        public Criteria and商品名称EqualTo(String value) {
            addCriterion("商品名称 =", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称NotEqualTo(String value) {
            addCriterion("商品名称 <>", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称GreaterThan(String value) {
            addCriterion("商品名称 >", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称GreaterThanOrEqualTo(String value) {
            addCriterion("商品名称 >=", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称LessThan(String value) {
            addCriterion("商品名称 <", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称LessThanOrEqualTo(String value) {
            addCriterion("商品名称 <=", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称Like(String value) {
            addCriterion("商品名称 like", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称NotLike(String value) {
            addCriterion("商品名称 not like", value, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称In(List<String> values) {
            addCriterion("商品名称 in", values, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称NotIn(List<String> values) {
            addCriterion("商品名称 not in", values, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称Between(String value1, String value2) {
            addCriterion("商品名称 between", value1, value2, "商品名称");
            return (Criteria) this;
        }

        public Criteria and商品名称NotBetween(String value1, String value2) {
            addCriterion("商品名称 not between", value1, value2, "商品名称");
            return (Criteria) this;
        }

        public Criteria and税抜金額IsNull() {
            addCriterion("税抜金額 is null");
            return (Criteria) this;
        }

        public Criteria and税抜金額IsNotNull() {
            addCriterion("税抜金額 is not null");
            return (Criteria) this;
        }

        public Criteria and税抜金額EqualTo(Long value) {
            addCriterion("税抜金額 =", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額NotEqualTo(Long value) {
            addCriterion("税抜金額 <>", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額GreaterThan(Long value) {
            addCriterion("税抜金額 >", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額GreaterThanOrEqualTo(Long value) {
            addCriterion("税抜金額 >=", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額LessThan(Long value) {
            addCriterion("税抜金額 <", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額LessThanOrEqualTo(Long value) {
            addCriterion("税抜金額 <=", value, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額In(List<Long> values) {
            addCriterion("税抜金額 in", values, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額NotIn(List<Long> values) {
            addCriterion("税抜金額 not in", values, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額Between(Long value1, Long value2) {
            addCriterion("税抜金額 between", value1, value2, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and税抜金額NotBetween(Long value1, Long value2) {
            addCriterion("税抜金額 not between", value1, value2, "税抜金額");
            return (Criteria) this;
        }

        public Criteria and容量IsNull() {
            addCriterion("容量 is null");
            return (Criteria) this;
        }

        public Criteria and容量IsNotNull() {
            addCriterion("容量 is not null");
            return (Criteria) this;
        }

        public Criteria and容量EqualTo(Long value) {
            addCriterion("容量 =", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量NotEqualTo(Long value) {
            addCriterion("容量 <>", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量GreaterThan(Long value) {
            addCriterion("容量 >", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量GreaterThanOrEqualTo(Long value) {
            addCriterion("容量 >=", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量LessThan(Long value) {
            addCriterion("容量 <", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量LessThanOrEqualTo(Long value) {
            addCriterion("容量 <=", value, "容量");
            return (Criteria) this;
        }

        public Criteria and容量In(List<Long> values) {
            addCriterion("容量 in", values, "容量");
            return (Criteria) this;
        }

        public Criteria and容量NotIn(List<Long> values) {
            addCriterion("容量 not in", values, "容量");
            return (Criteria) this;
        }

        public Criteria and容量Between(Long value1, Long value2) {
            addCriterion("容量 between", value1, value2, "容量");
            return (Criteria) this;
        }

        public Criteria and容量NotBetween(Long value1, Long value2) {
            addCriterion("容量 not between", value1, value2, "容量");
            return (Criteria) this;
        }

        public Criteria and基本商品FIsNull() {
            addCriterion("基本商品_F is null");
            return (Criteria) this;
        }

        public Criteria and基本商品FIsNotNull() {
            addCriterion("基本商品_F is not null");
            return (Criteria) this;
        }

        public Criteria and基本商品FEqualTo(String value) {
            addCriterion("基本商品_F =", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotEqualTo(String value) {
            addCriterion("基本商品_F <>", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FGreaterThan(String value) {
            addCriterion("基本商品_F >", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FGreaterThanOrEqualTo(String value) {
            addCriterion("基本商品_F >=", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLessThan(String value) {
            addCriterion("基本商品_F <", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLessThanOrEqualTo(String value) {
            addCriterion("基本商品_F <=", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FLike(String value) {
            addCriterion("基本商品_F like", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotLike(String value) {
            addCriterion("基本商品_F not like", value, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FIn(List<String> values) {
            addCriterion("基本商品_F in", values, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotIn(List<String> values) {
            addCriterion("基本商品_F not in", values, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FBetween(String value1, String value2) {
            addCriterion("基本商品_F between", value1, value2, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and基本商品FNotBetween(String value1, String value2) {
            addCriterion("基本商品_F not between", value1, value2, "基本商品F");
            return (Criteria) this;
        }

        public Criteria and非表示FIsNull() {
            addCriterion("非表示_F is null");
            return (Criteria) this;
        }

        public Criteria and非表示FIsNotNull() {
            addCriterion("非表示_F is not null");
            return (Criteria) this;
        }

        public Criteria and非表示FEqualTo(String value) {
            addCriterion("非表示_F =", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FNotEqualTo(String value) {
            addCriterion("非表示_F <>", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FGreaterThan(String value) {
            addCriterion("非表示_F >", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FGreaterThanOrEqualTo(String value) {
            addCriterion("非表示_F >=", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FLessThan(String value) {
            addCriterion("非表示_F <", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FLessThanOrEqualTo(String value) {
            addCriterion("非表示_F <=", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FLike(String value) {
            addCriterion("非表示_F like", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FNotLike(String value) {
            addCriterion("非表示_F not like", value, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FIn(List<String> values) {
            addCriterion("非表示_F in", values, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FNotIn(List<String> values) {
            addCriterion("非表示_F not in", values, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FBetween(String value1, String value2) {
            addCriterion("非表示_F between", value1, value2, "非表示F");
            return (Criteria) this;
        }

        public Criteria and非表示FNotBetween(String value1, String value2) {
            addCriterion("非表示_F not between", value1, value2, "非表示F");
            return (Criteria) this;
        }

        public Criteria and当月有効FIsNull() {
            addCriterion("当月有効_F is null");
            return (Criteria) this;
        }

        public Criteria and当月有効FIsNotNull() {
            addCriterion("当月有効_F is not null");
            return (Criteria) this;
        }

        public Criteria and当月有効FEqualTo(String value) {
            addCriterion("当月有効_F =", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FNotEqualTo(String value) {
            addCriterion("当月有効_F <>", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FGreaterThan(String value) {
            addCriterion("当月有効_F >", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FGreaterThanOrEqualTo(String value) {
            addCriterion("当月有効_F >=", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FLessThan(String value) {
            addCriterion("当月有効_F <", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FLessThanOrEqualTo(String value) {
            addCriterion("当月有効_F <=", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FLike(String value) {
            addCriterion("当月有効_F like", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FNotLike(String value) {
            addCriterion("当月有効_F not like", value, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FIn(List<String> values) {
            addCriterion("当月有効_F in", values, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FNotIn(List<String> values) {
            addCriterion("当月有効_F not in", values, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FBetween(String value1, String value2) {
            addCriterion("当月有効_F between", value1, value2, "当月有効F");
            return (Criteria) this;
        }

        public Criteria and当月有効FNotBetween(String value1, String value2) {
            addCriterion("当月有効_F not between", value1, value2, "当月有効F");
            return (Criteria) this;
        }

        public Criteria andグループcdIsNull() {
            addCriterion("グループCD is null");
            return (Criteria) this;
        }

        public Criteria andグループcdIsNotNull() {
            addCriterion("グループCD is not null");
            return (Criteria) this;
        }

        public Criteria andグループcdEqualTo(String value) {
            addCriterion("グループCD =", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdNotEqualTo(String value) {
            addCriterion("グループCD <>", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdGreaterThan(String value) {
            addCriterion("グループCD >", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdGreaterThanOrEqualTo(String value) {
            addCriterion("グループCD >=", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdLessThan(String value) {
            addCriterion("グループCD <", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdLessThanOrEqualTo(String value) {
            addCriterion("グループCD <=", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdLike(String value) {
            addCriterion("グループCD like", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdNotLike(String value) {
            addCriterion("グループCD not like", value, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdIn(List<String> values) {
            addCriterion("グループCD in", values, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdNotIn(List<String> values) {
            addCriterion("グループCD not in", values, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdBetween(String value1, String value2) {
            addCriterion("グループCD between", value1, value2, "グループcd");
            return (Criteria) this;
        }

        public Criteria andグループcdNotBetween(String value1, String value2) {
            addCriterion("グループCD not between", value1, value2, "グループcd");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNull() {
            addCriterion("登録ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIsNotNull() {
            addCriterion("登録ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidEqualTo(String value) {
            addCriterion("登録ユーザID =", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotEqualTo(String value) {
            addCriterion("登録ユーザID <>", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThan(String value) {
            addCriterion("登録ユーザID >", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("登録ユーザID >=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThan(String value) {
            addCriterion("登録ユーザID <", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLessThanOrEqualTo(String value) {
            addCriterion("登録ユーザID <=", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidLike(String value) {
            addCriterion("登録ユーザID like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotLike(String value) {
            addCriterion("登録ユーザID not like", value, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidIn(List<String> values) {
            addCriterion("登録ユーザID in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotIn(List<String> values) {
            addCriterion("登録ユーザID not in", values, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidBetween(String value1, String value2) {
            addCriterion("登録ユーザID between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録ユーザidNotBetween(String value1, String value2) {
            addCriterion("登録ユーザID not between", value1, value2, "登録ユーザid");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNull() {
            addCriterion("登録日時 is null");
            return (Criteria) this;
        }

        public Criteria and登録日時IsNotNull() {
            addCriterion("登録日時 is not null");
            return (Criteria) this;
        }

        public Criteria and登録日時EqualTo(Date value) {
            addCriterion("登録日時 =", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotEqualTo(Date value) {
            addCriterion("登録日時 <>", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThan(Date value) {
            addCriterion("登録日時 >", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時GreaterThanOrEqualTo(Date value) {
            addCriterion("登録日時 >=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThan(Date value) {
            addCriterion("登録日時 <", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時LessThanOrEqualTo(Date value) {
            addCriterion("登録日時 <=", value, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時In(List<Date> values) {
            addCriterion("登録日時 in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotIn(List<Date> values) {
            addCriterion("登録日時 not in", values, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時Between(Date value1, Date value2) {
            addCriterion("登録日時 between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and登録日時NotBetween(Date value1, Date value2) {
            addCriterion("登録日時 not between", value1, value2, "登録日時");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNull() {
            addCriterion("更新ユーザID is null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIsNotNull() {
            addCriterion("更新ユーザID is not null");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidEqualTo(String value) {
            addCriterion("更新ユーザID =", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotEqualTo(String value) {
            addCriterion("更新ユーザID <>", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThan(String value) {
            addCriterion("更新ユーザID >", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidGreaterThanOrEqualTo(String value) {
            addCriterion("更新ユーザID >=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThan(String value) {
            addCriterion("更新ユーザID <", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLessThanOrEqualTo(String value) {
            addCriterion("更新ユーザID <=", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidLike(String value) {
            addCriterion("更新ユーザID like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotLike(String value) {
            addCriterion("更新ユーザID not like", value, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidIn(List<String> values) {
            addCriterion("更新ユーザID in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotIn(List<String> values) {
            addCriterion("更新ユーザID not in", values, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidBetween(String value1, String value2) {
            addCriterion("更新ユーザID between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新ユーザidNotBetween(String value1, String value2) {
            addCriterion("更新ユーザID not between", value1, value2, "更新ユーザid");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNull() {
            addCriterion("更新日時 is null");
            return (Criteria) this;
        }

        public Criteria and更新日時IsNotNull() {
            addCriterion("更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria and更新日時EqualTo(Date value) {
            addCriterion("更新日時 =", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotEqualTo(Date value) {
            addCriterion("更新日時 <>", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThan(Date value) {
            addCriterion("更新日時 >", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("更新日時 >=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThan(Date value) {
            addCriterion("更新日時 <", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時LessThanOrEqualTo(Date value) {
            addCriterion("更新日時 <=", value, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時In(List<Date> values) {
            addCriterion("更新日時 in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotIn(List<Date> values) {
            addCriterion("更新日時 not in", values, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時Between(Date value1, Date value2) {
            addCriterion("更新日時 between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新日時NotBetween(Date value1, Date value2) {
            addCriterion("更新日時 not between", value1, value2, "更新日時");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNull() {
            addCriterion("更新プログラムID is null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIsNotNull() {
            addCriterion("更新プログラムID is not null");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidEqualTo(String value) {
            addCriterion("更新プログラムID =", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotEqualTo(String value) {
            addCriterion("更新プログラムID <>", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThan(String value) {
            addCriterion("更新プログラムID >", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidGreaterThanOrEqualTo(String value) {
            addCriterion("更新プログラムID >=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThan(String value) {
            addCriterion("更新プログラムID <", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLessThanOrEqualTo(String value) {
            addCriterion("更新プログラムID <=", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidLike(String value) {
            addCriterion("更新プログラムID like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotLike(String value) {
            addCriterion("更新プログラムID not like", value, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidIn(List<String> values) {
            addCriterion("更新プログラムID in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotIn(List<String> values) {
            addCriterion("更新プログラムID not in", values, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidBetween(String value1, String value2) {
            addCriterion("更新プログラムID between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria and更新プログラムidNotBetween(String value1, String value2) {
            addCriterion("更新プログラムID not between", value1, value2, "更新プログラムid");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNull() {
            addCriterion("バッチ更新日時 is null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時IsNotNull() {
            addCriterion("バッチ更新日時 is not null");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時EqualTo(Date value) {
            addCriterion("バッチ更新日時 =", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotEqualTo(Date value) {
            addCriterion("バッチ更新日時 <>", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThan(Date value) {
            addCriterion("バッチ更新日時 >", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時GreaterThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 >=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThan(Date value) {
            addCriterion("バッチ更新日時 <", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時LessThanOrEqualTo(Date value) {
            addCriterion("バッチ更新日時 <=", value, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時In(List<Date> values) {
            addCriterion("バッチ更新日時 in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotIn(List<Date> values) {
            addCriterion("バッチ更新日時 not in", values, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時Between(Date value1, Date value2) {
            addCriterion("バッチ更新日時 between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }

        public Criteria andバッチ更新日時NotBetween(Date value1, Date value2) {
            addCriterion("バッチ更新日時 not between", value1, value2, "バッチ更新日時");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品マスタ
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table 商品マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}