package foo.sample.db.auto.crud;

import java.util.List;
import foo.sample.db.auto.model.CampaignMaster;
import foo.sample.db.auto.model.CampaignMasterExample;
import foo.sample.db.auto.model.CampaignMasterKey;

public interface CampaignMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGN_MASTER
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    long countByExample(CampaignMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGN_MASTER
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    List<CampaignMaster> selectByExample(CampaignMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAMPAIGN_MASTER
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    CampaignMaster selectByPrimaryKey(CampaignMasterKey key);
}