package foo.sample.db.auto.crud;

import java.util.List;
import foo.sample.db.auto.model.ProvisioningLog;
import foo.sample.db.auto.model.ProvisioningLogExample;

public interface ProvisioningLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVISIONING_LOG
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    long countByExample(ProvisioningLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVISIONING_LOG
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    int insert(ProvisioningLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVISIONING_LOG
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    int insertSelective(ProvisioningLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVISIONING_LOG
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    List<ProvisioningLog> selectByExample(ProvisioningLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROVISIONING_LOG
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    ProvisioningLog selectByPrimaryKey(Integer seqno);
}