package foo.sample.db.auto.model;

public class CampaignMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.CAMPAIGN_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String campaignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String catvCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.SP_ID
     *
     * @return the value of CAMPAIGN_MASTER.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.SP_ID
     *
     * @param spId the value for CAMPAIGN_MASTER.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setSpId(String spId) {
        this.spId = spId == null ? null : spId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.CAMPAIGN_ID
     *
     * @return the value of CAMPAIGN_MASTER.CAMPAIGN_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.CAMPAIGN_ID
     *
     * @param campaignId the value for CAMPAIGN_MASTER.CAMPAIGN_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setCampaignId(String campaignId) {
        this.campaignId = campaignId == null ? null : campaignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.CATV_CODE
     *
     * @return the value of CAMPAIGN_MASTER.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getCatvCode() {
        return catvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.CATV_CODE
     *
     * @param catvCode the value for CAMPAIGN_MASTER.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setCatvCode(String catvCode) {
        this.catvCode = catvCode == null ? null : catvCode.trim();
    }
}