package foo.sample.db.auto.model;

import java.util.Date;

public class CampaignMaster extends CampaignMasterKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.CAMPAIGN_START_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Date campaignStartAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.CAMPAIGN_END_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Date campaignEndAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.INSERT_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Date insertAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAMPAIGN_MASTER.UPDATE_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.CAMPAIGN_START_AT
     *
     * @return the value of CAMPAIGN_MASTER.CAMPAIGN_START_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Date getCampaignStartAt() {
        return campaignStartAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.CAMPAIGN_START_AT
     *
     * @param campaignStartAt the value for CAMPAIGN_MASTER.CAMPAIGN_START_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setCampaignStartAt(Date campaignStartAt) {
        this.campaignStartAt = campaignStartAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.CAMPAIGN_END_AT
     *
     * @return the value of CAMPAIGN_MASTER.CAMPAIGN_END_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Date getCampaignEndAt() {
        return campaignEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.CAMPAIGN_END_AT
     *
     * @param campaignEndAt the value for CAMPAIGN_MASTER.CAMPAIGN_END_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setCampaignEndAt(Date campaignEndAt) {
        this.campaignEndAt = campaignEndAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.INSERT_AT
     *
     * @return the value of CAMPAIGN_MASTER.INSERT_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Date getInsertAt() {
        return insertAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.INSERT_AT
     *
     * @param insertAt the value for CAMPAIGN_MASTER.INSERT_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setInsertAt(Date insertAt) {
        this.insertAt = insertAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAMPAIGN_MASTER.UPDATE_AT
     *
     * @return the value of CAMPAIGN_MASTER.UPDATE_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAMPAIGN_MASTER.UPDATE_AT
     *
     * @param updateAt the value for CAMPAIGN_MASTER.UPDATE_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}