package foo.sample.db.auto.model;

import java.util.Date;

public class ProvisioningLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.SEQNO
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Integer seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String catvCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.LOG_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private Date logAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.SUBSCRIBER_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String subscriberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.OPERATE_TYPE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.OPERATE_TARGET
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String operateTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.OPERATE_CONTENTS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String operateContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.RESULT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROVISIONING_LOG.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    private String spId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.SEQNO
     *
     * @return the value of PROVISIONING_LOG.SEQNO
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.SEQNO
     *
     * @param seqno the value for PROVISIONING_LOG.SEQNO
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.CATV_CODE
     *
     * @return the value of PROVISIONING_LOG.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getCatvCode() {
        return catvCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.CATV_CODE
     *
     * @param catvCode the value for PROVISIONING_LOG.CATV_CODE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setCatvCode(String catvCode) {
        this.catvCode = catvCode == null ? null : catvCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.LOG_AT
     *
     * @return the value of PROVISIONING_LOG.LOG_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Date getLogAt() {
        return logAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.LOG_AT
     *
     * @param logAt the value for PROVISIONING_LOG.LOG_AT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setLogAt(Date logAt) {
        this.logAt = logAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.SUBSCRIBER_ID
     *
     * @return the value of PROVISIONING_LOG.SUBSCRIBER_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getSubscriberId() {
        return subscriberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.SUBSCRIBER_ID
     *
     * @param subscriberId the value for PROVISIONING_LOG.SUBSCRIBER_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setSubscriberId(String subscriberId) {
        this.subscriberId = subscriberId == null ? null : subscriberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.OPERATE_TYPE
     *
     * @return the value of PROVISIONING_LOG.OPERATE_TYPE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.OPERATE_TYPE
     *
     * @param operateType the value for PROVISIONING_LOG.OPERATE_TYPE
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.OPERATE_TARGET
     *
     * @return the value of PROVISIONING_LOG.OPERATE_TARGET
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getOperateTarget() {
        return operateTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.OPERATE_TARGET
     *
     * @param operateTarget the value for PROVISIONING_LOG.OPERATE_TARGET
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setOperateTarget(String operateTarget) {
        this.operateTarget = operateTarget == null ? null : operateTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.OPERATE_CONTENTS
     *
     * @return the value of PROVISIONING_LOG.OPERATE_CONTENTS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getOperateContents() {
        return operateContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.OPERATE_CONTENTS
     *
     * @param operateContents the value for PROVISIONING_LOG.OPERATE_CONTENTS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setOperateContents(String operateContents) {
        this.operateContents = operateContents == null ? null : operateContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.RESULT
     *
     * @return the value of PROVISIONING_LOG.RESULT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.RESULT
     *
     * @param result the value for PROVISIONING_LOG.RESULT
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROVISIONING_LOG.SP_ID
     *
     * @return the value of PROVISIONING_LOG.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROVISIONING_LOG.SP_ID
     *
     * @param spId the value for PROVISIONING_LOG.SP_ID
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setSpId(String spId) {
        this.spId = spId == null ? null : spId.trim();
    }
}