package foo.sample.db.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServiceProvisioningExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public ServiceProvisioningExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Integer value) {
            addCriterion("SEQNO =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Integer value) {
            addCriterion("SEQNO <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Integer value) {
            addCriterion("SEQNO >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQNO >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Integer value) {
            addCriterion("SEQNO <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
            addCriterion("SEQNO <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Integer> values) {
            addCriterion("SEQNO in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Integer> values) {
            addCriterion("SEQNO not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Integer value1, Integer value2) {
            addCriterion("SEQNO between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQNO not between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIsNull() {
            addCriterion("SUBSCRIBER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIsNotNull() {
            addCriterion("SUBSCRIBER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID =", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID <>", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdGreaterThan(String value) {
            addCriterion("SUBSCRIBER_ID >", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID >=", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLessThan(String value) {
            addCriterion("SUBSCRIBER_ID <", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLessThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID <=", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLike(String value) {
            addCriterion("SUBSCRIBER_ID like", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotLike(String value) {
            addCriterion("SUBSCRIBER_ID not like", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIn(List<String> values) {
            addCriterion("SUBSCRIBER_ID in", values, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotIn(List<String> values) {
            addCriterion("SUBSCRIBER_ID not in", values, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdBetween(String value1, String value2) {
            addCriterion("SUBSCRIBER_ID between", value1, value2, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotBetween(String value1, String value2) {
            addCriterion("SUBSCRIBER_ID not between", value1, value2, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("OPERATE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("OPERATE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(String value) {
            addCriterion("OPERATE_TYPE =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(String value) {
            addCriterion("OPERATE_TYPE <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(String value) {
            addCriterion("OPERATE_TYPE >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATE_TYPE >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(String value) {
            addCriterion("OPERATE_TYPE <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(String value) {
            addCriterion("OPERATE_TYPE <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLike(String value) {
            addCriterion("OPERATE_TYPE like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotLike(String value) {
            addCriterion("OPERATE_TYPE not like", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<String> values) {
            addCriterion("OPERATE_TYPE in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<String> values) {
            addCriterion("OPERATE_TYPE not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(String value1, String value2) {
            addCriterion("OPERATE_TYPE between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(String value1, String value2) {
            addCriterion("OPERATE_TYPE not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNull() {
            addCriterion("RESULT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNotNull() {
            addCriterion("RESULT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andResultCodeEqualTo(String value) {
            addCriterion("RESULT_CODE =", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotEqualTo(String value) {
            addCriterion("RESULT_CODE <>", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThan(String value) {
            addCriterion("RESULT_CODE >", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT_CODE >=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThan(String value) {
            addCriterion("RESULT_CODE <", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThanOrEqualTo(String value) {
            addCriterion("RESULT_CODE <=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLike(String value) {
            addCriterion("RESULT_CODE like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotLike(String value) {
            addCriterion("RESULT_CODE not like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeIn(List<String> values) {
            addCriterion("RESULT_CODE in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotIn(List<String> values) {
            addCriterion("RESULT_CODE not in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeBetween(String value1, String value2) {
            addCriterion("RESULT_CODE between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotBetween(String value1, String value2) {
            addCriterion("RESULT_CODE not between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIsNull() {
            addCriterion("CATV_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIsNotNull() {
            addCriterion("CATV_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCatvCodeEqualTo(String value) {
            addCriterion("CATV_CODE =", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotEqualTo(String value) {
            addCriterion("CATV_CODE <>", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeGreaterThan(String value) {
            addCriterion("CATV_CODE >", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CATV_CODE >=", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLessThan(String value) {
            addCriterion("CATV_CODE <", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLessThanOrEqualTo(String value) {
            addCriterion("CATV_CODE <=", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLike(String value) {
            addCriterion("CATV_CODE like", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotLike(String value) {
            addCriterion("CATV_CODE not like", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIn(List<String> values) {
            addCriterion("CATV_CODE in", values, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotIn(List<String> values) {
            addCriterion("CATV_CODE not in", values, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeBetween(String value1, String value2) {
            addCriterion("CATV_CODE between", value1, value2, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotBetween(String value1, String value2) {
            addCriterion("CATV_CODE not between", value1, value2, "catvCode");
            return (Criteria) this;
        }

        public Criteria andPersonalIdIsNull() {
            addCriterion("PERSONAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andPersonalIdIsNotNull() {
            addCriterion("PERSONAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalIdEqualTo(String value) {
            addCriterion("PERSONAL_ID =", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdNotEqualTo(String value) {
            addCriterion("PERSONAL_ID <>", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdGreaterThan(String value) {
            addCriterion("PERSONAL_ID >", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONAL_ID >=", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdLessThan(String value) {
            addCriterion("PERSONAL_ID <", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdLessThanOrEqualTo(String value) {
            addCriterion("PERSONAL_ID <=", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdLike(String value) {
            addCriterion("PERSONAL_ID like", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdNotLike(String value) {
            addCriterion("PERSONAL_ID not like", value, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdIn(List<String> values) {
            addCriterion("PERSONAL_ID in", values, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdNotIn(List<String> values) {
            addCriterion("PERSONAL_ID not in", values, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdBetween(String value1, String value2) {
            addCriterion("PERSONAL_ID between", value1, value2, "personalId");
            return (Criteria) this;
        }

        public Criteria andPersonalIdNotBetween(String value1, String value2) {
            addCriterion("PERSONAL_ID not between", value1, value2, "personalId");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeIsNull() {
            addCriterion("COMMON_PRODUCT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeIsNotNull() {
            addCriterion("COMMON_PRODUCT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeEqualTo(String value) {
            addCriterion("COMMON_PRODUCT_CODE =", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeNotEqualTo(String value) {
            addCriterion("COMMON_PRODUCT_CODE <>", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeGreaterThan(String value) {
            addCriterion("COMMON_PRODUCT_CODE >", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("COMMON_PRODUCT_CODE >=", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeLessThan(String value) {
            addCriterion("COMMON_PRODUCT_CODE <", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeLessThanOrEqualTo(String value) {
            addCriterion("COMMON_PRODUCT_CODE <=", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeLike(String value) {
            addCriterion("COMMON_PRODUCT_CODE like", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeNotLike(String value) {
            addCriterion("COMMON_PRODUCT_CODE not like", value, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeIn(List<String> values) {
            addCriterion("COMMON_PRODUCT_CODE in", values, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeNotIn(List<String> values) {
            addCriterion("COMMON_PRODUCT_CODE not in", values, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeBetween(String value1, String value2) {
            addCriterion("COMMON_PRODUCT_CODE between", value1, value2, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andCommonProductCodeNotBetween(String value1, String value2) {
            addCriterion("COMMON_PRODUCT_CODE not between", value1, value2, "commonProductCode");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagIsNull() {
            addCriterion("SUSPEND_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagIsNotNull() {
            addCriterion("SUSPEND_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagEqualTo(String value) {
            addCriterion("SUSPEND_FLAG =", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagNotEqualTo(String value) {
            addCriterion("SUSPEND_FLAG <>", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagGreaterThan(String value) {
            addCriterion("SUSPEND_FLAG >", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SUSPEND_FLAG >=", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagLessThan(String value) {
            addCriterion("SUSPEND_FLAG <", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagLessThanOrEqualTo(String value) {
            addCriterion("SUSPEND_FLAG <=", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagLike(String value) {
            addCriterion("SUSPEND_FLAG like", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagNotLike(String value) {
            addCriterion("SUSPEND_FLAG not like", value, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagIn(List<String> values) {
            addCriterion("SUSPEND_FLAG in", values, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagNotIn(List<String> values) {
            addCriterion("SUSPEND_FLAG not in", values, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagBetween(String value1, String value2) {
            addCriterion("SUSPEND_FLAG between", value1, value2, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andSuspendFlagNotBetween(String value1, String value2) {
            addCriterion("SUSPEND_FLAG not between", value1, value2, "suspendFlag");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNull() {
            addCriterion("DUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDueDateIsNotNull() {
            addCriterion("DUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDueDateEqualTo(Date value) {
            addCriterion("DUE_DATE =", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotEqualTo(Date value) {
            addCriterion("DUE_DATE <>", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThan(Date value) {
            addCriterion("DUE_DATE >", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateGreaterThanOrEqualTo(Date value) {
            addCriterion("DUE_DATE >=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThan(Date value) {
            addCriterion("DUE_DATE <", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateLessThanOrEqualTo(Date value) {
            addCriterion("DUE_DATE <=", value, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateIn(List<Date> values) {
            addCriterion("DUE_DATE in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotIn(List<Date> values) {
            addCriterion("DUE_DATE not in", values, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateBetween(Date value1, Date value2) {
            addCriterion("DUE_DATE between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andDueDateNotBetween(Date value1, Date value2) {
            addCriterion("DUE_DATE not between", value1, value2, "dueDate");
            return (Criteria) this;
        }

        public Criteria andCableIdIsNull() {
            addCriterion("CABLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCableIdIsNotNull() {
            addCriterion("CABLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCableIdEqualTo(String value) {
            addCriterion("CABLE_ID =", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotEqualTo(String value) {
            addCriterion("CABLE_ID <>", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdGreaterThan(String value) {
            addCriterion("CABLE_ID >", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdGreaterThanOrEqualTo(String value) {
            addCriterion("CABLE_ID >=", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLessThan(String value) {
            addCriterion("CABLE_ID <", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLessThanOrEqualTo(String value) {
            addCriterion("CABLE_ID <=", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLike(String value) {
            addCriterion("CABLE_ID like", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotLike(String value) {
            addCriterion("CABLE_ID not like", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdIn(List<String> values) {
            addCriterion("CABLE_ID in", values, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotIn(List<String> values) {
            addCriterion("CABLE_ID not in", values, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdBetween(String value1, String value2) {
            addCriterion("CABLE_ID between", value1, value2, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotBetween(String value1, String value2) {
            addCriterion("CABLE_ID not between", value1, value2, "cableId");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNull() {
            addCriterion("FULL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFullNameIsNotNull() {
            addCriterion("FULL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFullNameEqualTo(String value) {
            addCriterion("FULL_NAME =", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("FULL_NAME <>", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("FULL_NAME >", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("FULL_NAME >=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThan(String value) {
            addCriterion("FULL_NAME <", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("FULL_NAME <=", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameLike(String value) {
            addCriterion("FULL_NAME like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotLike(String value) {
            addCriterion("FULL_NAME not like", value, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameIn(List<String> values) {
            addCriterion("FULL_NAME in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("FULL_NAME not in", values, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("FULL_NAME between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("FULL_NAME not between", value1, value2, "fullName");
            return (Criteria) this;
        }

        public Criteria andFullKanaIsNull() {
            addCriterion("FULL_KANA is null");
            return (Criteria) this;
        }

        public Criteria andFullKanaIsNotNull() {
            addCriterion("FULL_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andFullKanaEqualTo(String value) {
            addCriterion("FULL_KANA =", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaNotEqualTo(String value) {
            addCriterion("FULL_KANA <>", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaGreaterThan(String value) {
            addCriterion("FULL_KANA >", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaGreaterThanOrEqualTo(String value) {
            addCriterion("FULL_KANA >=", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaLessThan(String value) {
            addCriterion("FULL_KANA <", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaLessThanOrEqualTo(String value) {
            addCriterion("FULL_KANA <=", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaLike(String value) {
            addCriterion("FULL_KANA like", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaNotLike(String value) {
            addCriterion("FULL_KANA not like", value, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaIn(List<String> values) {
            addCriterion("FULL_KANA in", values, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaNotIn(List<String> values) {
            addCriterion("FULL_KANA not in", values, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaBetween(String value1, String value2) {
            addCriterion("FULL_KANA between", value1, value2, "fullKana");
            return (Criteria) this;
        }

        public Criteria andFullKanaNotBetween(String value1, String value2) {
            addCriterion("FULL_KANA not between", value1, value2, "fullKana");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNull() {
            addCriterion("POST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPostCodeIsNotNull() {
            addCriterion("POST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPostCodeEqualTo(String value) {
            addCriterion("POST_CODE =", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotEqualTo(String value) {
            addCriterion("POST_CODE <>", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThan(String value) {
            addCriterion("POST_CODE >", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("POST_CODE >=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThan(String value) {
            addCriterion("POST_CODE <", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLessThanOrEqualTo(String value) {
            addCriterion("POST_CODE <=", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeLike(String value) {
            addCriterion("POST_CODE like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotLike(String value) {
            addCriterion("POST_CODE not like", value, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeIn(List<String> values) {
            addCriterion("POST_CODE in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotIn(List<String> values) {
            addCriterion("POST_CODE not in", values, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeBetween(String value1, String value2) {
            addCriterion("POST_CODE between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andPostCodeNotBetween(String value1, String value2) {
            addCriterion("POST_CODE not between", value1, value2, "postCode");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNull() {
            addCriterion("MAIL_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNotNull() {
            addCriterion("MAIL_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andMailAddressEqualTo(String value) {
            addCriterion("MAIL_ADDRESS =", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotEqualTo(String value) {
            addCriterion("MAIL_ADDRESS <>", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThan(String value) {
            addCriterion("MAIL_ADDRESS >", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDRESS >=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThan(String value) {
            addCriterion("MAIL_ADDRESS <", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDRESS <=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLike(String value) {
            addCriterion("MAIL_ADDRESS like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotLike(String value) {
            addCriterion("MAIL_ADDRESS not like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressIn(List<String> values) {
            addCriterion("MAIL_ADDRESS in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotIn(List<String> values) {
            addCriterion("MAIL_ADDRESS not in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressBetween(String value1, String value2) {
            addCriterion("MAIL_ADDRESS between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotBetween(String value1, String value2) {
            addCriterion("MAIL_ADDRESS not between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdIsNull() {
            addCriterion("SMS_CONTRACT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdIsNotNull() {
            addCriterion("SMS_CONTRACT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdEqualTo(String value) {
            addCriterion("SMS_CONTRACT_ID =", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdNotEqualTo(String value) {
            addCriterion("SMS_CONTRACT_ID <>", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdGreaterThan(String value) {
            addCriterion("SMS_CONTRACT_ID >", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CONTRACT_ID >=", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdLessThan(String value) {
            addCriterion("SMS_CONTRACT_ID <", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_CONTRACT_ID <=", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdLike(String value) {
            addCriterion("SMS_CONTRACT_ID like", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdNotLike(String value) {
            addCriterion("SMS_CONTRACT_ID not like", value, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdIn(List<String> values) {
            addCriterion("SMS_CONTRACT_ID in", values, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdNotIn(List<String> values) {
            addCriterion("SMS_CONTRACT_ID not in", values, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdBetween(String value1, String value2) {
            addCriterion("SMS_CONTRACT_ID between", value1, value2, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractIdNotBetween(String value1, String value2) {
            addCriterion("SMS_CONTRACT_ID not between", value1, value2, "smsContractId");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagIsNull() {
            addCriterion("SMS_CONTRACT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagIsNotNull() {
            addCriterion("SMS_CONTRACT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagEqualTo(String value) {
            addCriterion("SMS_CONTRACT_FLAG =", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagNotEqualTo(String value) {
            addCriterion("SMS_CONTRACT_FLAG <>", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagGreaterThan(String value) {
            addCriterion("SMS_CONTRACT_FLAG >", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CONTRACT_FLAG >=", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagLessThan(String value) {
            addCriterion("SMS_CONTRACT_FLAG <", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagLessThanOrEqualTo(String value) {
            addCriterion("SMS_CONTRACT_FLAG <=", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagLike(String value) {
            addCriterion("SMS_CONTRACT_FLAG like", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagNotLike(String value) {
            addCriterion("SMS_CONTRACT_FLAG not like", value, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagIn(List<String> values) {
            addCriterion("SMS_CONTRACT_FLAG in", values, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagNotIn(List<String> values) {
            addCriterion("SMS_CONTRACT_FLAG not in", values, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagBetween(String value1, String value2) {
            addCriterion("SMS_CONTRACT_FLAG between", value1, value2, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andSmsContractFlagNotBetween(String value1, String value2) {
            addCriterion("SMS_CONTRACT_FLAG not between", value1, value2, "smsContractFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagIsNull() {
            addCriterion("AUTHORIZE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagIsNotNull() {
            addCriterion("AUTHORIZE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagEqualTo(String value) {
            addCriterion("AUTHORIZE_FLAG =", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagNotEqualTo(String value) {
            addCriterion("AUTHORIZE_FLAG <>", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagGreaterThan(String value) {
            addCriterion("AUTHORIZE_FLAG >", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHORIZE_FLAG >=", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagLessThan(String value) {
            addCriterion("AUTHORIZE_FLAG <", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagLessThanOrEqualTo(String value) {
            addCriterion("AUTHORIZE_FLAG <=", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagLike(String value) {
            addCriterion("AUTHORIZE_FLAG like", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagNotLike(String value) {
            addCriterion("AUTHORIZE_FLAG not like", value, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagIn(List<String> values) {
            addCriterion("AUTHORIZE_FLAG in", values, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagNotIn(List<String> values) {
            addCriterion("AUTHORIZE_FLAG not in", values, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagBetween(String value1, String value2) {
            addCriterion("AUTHORIZE_FLAG between", value1, value2, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andAuthorizeFlagNotBetween(String value1, String value2) {
            addCriterion("AUTHORIZE_FLAG not between", value1, value2, "authorizeFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNull() {
            addCriterion("ENABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIsNotNull() {
            addCriterion("ENABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEnableFlagEqualTo(String value) {
            addCriterion("ENABLE_FLAG =", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotEqualTo(String value) {
            addCriterion("ENABLE_FLAG <>", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThan(String value) {
            addCriterion("ENABLE_FLAG >", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ENABLE_FLAG >=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThan(String value) {
            addCriterion("ENABLE_FLAG <", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLessThanOrEqualTo(String value) {
            addCriterion("ENABLE_FLAG <=", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagLike(String value) {
            addCriterion("ENABLE_FLAG like", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotLike(String value) {
            addCriterion("ENABLE_FLAG not like", value, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagIn(List<String> values) {
            addCriterion("ENABLE_FLAG in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotIn(List<String> values) {
            addCriterion("ENABLE_FLAG not in", values, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagBetween(String value1, String value2) {
            addCriterion("ENABLE_FLAG between", value1, value2, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andEnableFlagNotBetween(String value1, String value2) {
            addCriterion("ENABLE_FLAG not between", value1, value2, "enableFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagIsNull() {
            addCriterion("CONSENT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andConsentFlagIsNotNull() {
            addCriterion("CONSENT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andConsentFlagEqualTo(String value) {
            addCriterion("CONSENT_FLAG =", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagNotEqualTo(String value) {
            addCriterion("CONSENT_FLAG <>", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagGreaterThan(String value) {
            addCriterion("CONSENT_FLAG >", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CONSENT_FLAG >=", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagLessThan(String value) {
            addCriterion("CONSENT_FLAG <", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagLessThanOrEqualTo(String value) {
            addCriterion("CONSENT_FLAG <=", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagLike(String value) {
            addCriterion("CONSENT_FLAG like", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagNotLike(String value) {
            addCriterion("CONSENT_FLAG not like", value, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagIn(List<String> values) {
            addCriterion("CONSENT_FLAG in", values, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagNotIn(List<String> values) {
            addCriterion("CONSENT_FLAG not in", values, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagBetween(String value1, String value2) {
            addCriterion("CONSENT_FLAG between", value1, value2, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andConsentFlagNotBetween(String value1, String value2) {
            addCriterion("CONSENT_FLAG not between", value1, value2, "consentFlag");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNull() {
            addCriterion("SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(String value) {
            addCriterion("SP_ID =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(String value) {
            addCriterion("SP_ID <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(String value) {
            addCriterion("SP_ID >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ID >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(String value) {
            addCriterion("SP_ID <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ID <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLike(String value) {
            addCriterion("SP_ID like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotLike(String value) {
            addCriterion("SP_ID not like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<String> values) {
            addCriterion("SP_ID in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<String> values) {
            addCriterion("SP_ID not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(String value1, String value2) {
            addCriterion("SP_ID between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(String value1, String value2) {
            addCriterion("SP_ID not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdIsNull() {
            addCriterion("SP_ACCOUNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdIsNotNull() {
            addCriterion("SP_ACCOUNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdEqualTo(String value) {
            addCriterion("SP_ACCOUNT_ID =", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdNotEqualTo(String value) {
            addCriterion("SP_ACCOUNT_ID <>", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdGreaterThan(String value) {
            addCriterion("SP_ACCOUNT_ID >", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ACCOUNT_ID >=", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdLessThan(String value) {
            addCriterion("SP_ACCOUNT_ID <", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ACCOUNT_ID <=", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdLike(String value) {
            addCriterion("SP_ACCOUNT_ID like", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdNotLike(String value) {
            addCriterion("SP_ACCOUNT_ID not like", value, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdIn(List<String> values) {
            addCriterion("SP_ACCOUNT_ID in", values, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdNotIn(List<String> values) {
            addCriterion("SP_ACCOUNT_ID not in", values, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdBetween(String value1, String value2) {
            addCriterion("SP_ACCOUNT_ID between", value1, value2, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpAccountIdNotBetween(String value1, String value2) {
            addCriterion("SP_ACCOUNT_ID not between", value1, value2, "spAccountId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIsNull() {
            addCriterion("SP_CONTRACT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIsNotNull() {
            addCriterion("SP_CONTRACT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpContractIdEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID =", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID <>", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdGreaterThan(String value) {
            addCriterion("SP_CONTRACT_ID >", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID >=", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLessThan(String value) {
            addCriterion("SP_CONTRACT_ID <", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLessThanOrEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID <=", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLike(String value) {
            addCriterion("SP_CONTRACT_ID like", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotLike(String value) {
            addCriterion("SP_CONTRACT_ID not like", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIn(List<String> values) {
            addCriterion("SP_CONTRACT_ID in", values, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotIn(List<String> values) {
            addCriterion("SP_CONTRACT_ID not in", values, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdBetween(String value1, String value2) {
            addCriterion("SP_CONTRACT_ID between", value1, value2, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotBetween(String value1, String value2) {
            addCriterion("SP_CONTRACT_ID not between", value1, value2, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameIsNull() {
            addCriterion("SP_LINK_FILE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameIsNotNull() {
            addCriterion("SP_LINK_FILE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameEqualTo(String value) {
            addCriterion("SP_LINK_FILE_NAME =", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameNotEqualTo(String value) {
            addCriterion("SP_LINK_FILE_NAME <>", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameGreaterThan(String value) {
            addCriterion("SP_LINK_FILE_NAME >", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("SP_LINK_FILE_NAME >=", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameLessThan(String value) {
            addCriterion("SP_LINK_FILE_NAME <", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameLessThanOrEqualTo(String value) {
            addCriterion("SP_LINK_FILE_NAME <=", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameLike(String value) {
            addCriterion("SP_LINK_FILE_NAME like", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameNotLike(String value) {
            addCriterion("SP_LINK_FILE_NAME not like", value, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameIn(List<String> values) {
            addCriterion("SP_LINK_FILE_NAME in", values, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameNotIn(List<String> values) {
            addCriterion("SP_LINK_FILE_NAME not in", values, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameBetween(String value1, String value2) {
            addCriterion("SP_LINK_FILE_NAME between", value1, value2, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andSpLinkFileNameNotBetween(String value1, String value2) {
            addCriterion("SP_LINK_FILE_NAME not between", value1, value2, "spLinkFileName");
            return (Criteria) this;
        }

        public Criteria andInsertAtIsNull() {
            addCriterion("INSERT_AT is null");
            return (Criteria) this;
        }

        public Criteria andInsertAtIsNotNull() {
            addCriterion("INSERT_AT is not null");
            return (Criteria) this;
        }

        public Criteria andInsertAtEqualTo(Date value) {
            addCriterion("INSERT_AT =", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotEqualTo(Date value) {
            addCriterion("INSERT_AT <>", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtGreaterThan(Date value) {
            addCriterion("INSERT_AT >", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_AT >=", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtLessThan(Date value) {
            addCriterion("INSERT_AT <", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_AT <=", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtIn(List<Date> values) {
            addCriterion("INSERT_AT in", values, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotIn(List<Date> values) {
            addCriterion("INSERT_AT not in", values, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtBetween(Date value1, Date value2) {
            addCriterion("INSERT_AT between", value1, value2, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_AT not between", value1, value2, "insertAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("UPDATE_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("UPDATE_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("UPDATE_AT =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("UPDATE_AT <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("UPDATE_AT >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_AT >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("UPDATE_AT <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_AT <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("UPDATE_AT in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("UPDATE_AT not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("UPDATE_AT between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_AT not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 15:27:34 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SERVICE_PROVISIONING
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}