package foo.sample.db.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public UserStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCableIdIsNull() {
            addCriterion("CABLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCableIdIsNotNull() {
            addCriterion("CABLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCableIdEqualTo(String value) {
            addCriterion("CABLE_ID =", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotEqualTo(String value) {
            addCriterion("CABLE_ID <>", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdGreaterThan(String value) {
            addCriterion("CABLE_ID >", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdGreaterThanOrEqualTo(String value) {
            addCriterion("CABLE_ID >=", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLessThan(String value) {
            addCriterion("CABLE_ID <", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLessThanOrEqualTo(String value) {
            addCriterion("CABLE_ID <=", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdLike(String value) {
            addCriterion("CABLE_ID like", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotLike(String value) {
            addCriterion("CABLE_ID not like", value, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdIn(List<String> values) {
            addCriterion("CABLE_ID in", values, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotIn(List<String> values) {
            addCriterion("CABLE_ID not in", values, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdBetween(String value1, String value2) {
            addCriterion("CABLE_ID between", value1, value2, "cableId");
            return (Criteria) this;
        }

        public Criteria andCableIdNotBetween(String value1, String value2) {
            addCriterion("CABLE_ID not between", value1, value2, "cableId");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNull() {
            addCriterion("SP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("SP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(String value) {
            addCriterion("SP_ID =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(String value) {
            addCriterion("SP_ID <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(String value) {
            addCriterion("SP_ID >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_ID >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(String value) {
            addCriterion("SP_ID <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(String value) {
            addCriterion("SP_ID <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLike(String value) {
            addCriterion("SP_ID like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotLike(String value) {
            addCriterion("SP_ID not like", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<String> values) {
            addCriterion("SP_ID in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<String> values) {
            addCriterion("SP_ID not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(String value1, String value2) {
            addCriterion("SP_ID between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(String value1, String value2) {
            addCriterion("SP_ID not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIsNull() {
            addCriterion("CATV_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIsNotNull() {
            addCriterion("CATV_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCatvCodeEqualTo(String value) {
            addCriterion("CATV_CODE =", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotEqualTo(String value) {
            addCriterion("CATV_CODE <>", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeGreaterThan(String value) {
            addCriterion("CATV_CODE >", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CATV_CODE >=", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLessThan(String value) {
            addCriterion("CATV_CODE <", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLessThanOrEqualTo(String value) {
            addCriterion("CATV_CODE <=", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeLike(String value) {
            addCriterion("CATV_CODE like", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotLike(String value) {
            addCriterion("CATV_CODE not like", value, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeIn(List<String> values) {
            addCriterion("CATV_CODE in", values, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotIn(List<String> values) {
            addCriterion("CATV_CODE not in", values, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeBetween(String value1, String value2) {
            addCriterion("CATV_CODE between", value1, value2, "catvCode");
            return (Criteria) this;
        }

        public Criteria andCatvCodeNotBetween(String value1, String value2) {
            addCriterion("CATV_CODE not between", value1, value2, "catvCode");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIsNull() {
            addCriterion("SUBSCRIBER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIsNotNull() {
            addCriterion("SUBSCRIBER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID =", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID <>", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdGreaterThan(String value) {
            addCriterion("SUBSCRIBER_ID >", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID >=", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLessThan(String value) {
            addCriterion("SUBSCRIBER_ID <", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLessThanOrEqualTo(String value) {
            addCriterion("SUBSCRIBER_ID <=", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdLike(String value) {
            addCriterion("SUBSCRIBER_ID like", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotLike(String value) {
            addCriterion("SUBSCRIBER_ID not like", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdIn(List<String> values) {
            addCriterion("SUBSCRIBER_ID in", values, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotIn(List<String> values) {
            addCriterion("SUBSCRIBER_ID not in", values, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdBetween(String value1, String value2) {
            addCriterion("SUBSCRIBER_ID between", value1, value2, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSubscriberIdNotBetween(String value1, String value2) {
            addCriterion("SUBSCRIBER_ID not between", value1, value2, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIsNull() {
            addCriterion("SP_CONTRACT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIsNotNull() {
            addCriterion("SP_CONTRACT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpContractIdEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID =", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID <>", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdGreaterThan(String value) {
            addCriterion("SP_CONTRACT_ID >", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID >=", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLessThan(String value) {
            addCriterion("SP_CONTRACT_ID <", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLessThanOrEqualTo(String value) {
            addCriterion("SP_CONTRACT_ID <=", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdLike(String value) {
            addCriterion("SP_CONTRACT_ID like", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotLike(String value) {
            addCriterion("SP_CONTRACT_ID not like", value, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdIn(List<String> values) {
            addCriterion("SP_CONTRACT_ID in", values, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotIn(List<String> values) {
            addCriterion("SP_CONTRACT_ID not in", values, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdBetween(String value1, String value2) {
            addCriterion("SP_CONTRACT_ID between", value1, value2, "spContractId");
            return (Criteria) this;
        }

        public Criteria andSpContractIdNotBetween(String value1, String value2) {
            addCriterion("SP_CONTRACT_ID not between", value1, value2, "spContractId");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeIsNull() {
            addCriterion("USER_STATUS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeIsNotNull() {
            addCriterion("USER_STATUS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeEqualTo(String value) {
            addCriterion("USER_STATUS_CODE =", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeNotEqualTo(String value) {
            addCriterion("USER_STATUS_CODE <>", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeGreaterThan(String value) {
            addCriterion("USER_STATUS_CODE >", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_STATUS_CODE >=", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeLessThan(String value) {
            addCriterion("USER_STATUS_CODE <", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("USER_STATUS_CODE <=", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeLike(String value) {
            addCriterion("USER_STATUS_CODE like", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeNotLike(String value) {
            addCriterion("USER_STATUS_CODE not like", value, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeIn(List<String> values) {
            addCriterion("USER_STATUS_CODE in", values, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeNotIn(List<String> values) {
            addCriterion("USER_STATUS_CODE not in", values, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeBetween(String value1, String value2) {
            addCriterion("USER_STATUS_CODE between", value1, value2, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andUserStatusCodeNotBetween(String value1, String value2) {
            addCriterion("USER_STATUS_CODE not between", value1, value2, "userStatusCode");
            return (Criteria) this;
        }

        public Criteria andInsertAtIsNull() {
            addCriterion("INSERT_AT is null");
            return (Criteria) this;
        }

        public Criteria andInsertAtIsNotNull() {
            addCriterion("INSERT_AT is not null");
            return (Criteria) this;
        }

        public Criteria andInsertAtEqualTo(Date value) {
            addCriterion("INSERT_AT =", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotEqualTo(Date value) {
            addCriterion("INSERT_AT <>", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtGreaterThan(Date value) {
            addCriterion("INSERT_AT >", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_AT >=", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtLessThan(Date value) {
            addCriterion("INSERT_AT <", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_AT <=", value, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtIn(List<Date> values) {
            addCriterion("INSERT_AT in", values, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotIn(List<Date> values) {
            addCriterion("INSERT_AT not in", values, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtBetween(Date value1, Date value2) {
            addCriterion("INSERT_AT between", value1, value2, "insertAt");
            return (Criteria) this;
        }

        public Criteria andInsertAtNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_AT not between", value1, value2, "insertAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("UPDATE_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("UPDATE_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("UPDATE_AT =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("UPDATE_AT <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("UPDATE_AT >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_AT >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("UPDATE_AT <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_AT <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("UPDATE_AT in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("UPDATE_AT not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("UPDATE_AT between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_AT not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_STATUS
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 26 15:27:34 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_STATUS
     *
     * @mbg.generated Wed Dec 26 15:27:34 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}