package foo.sample.db.auto.ref.crud;

import java.util.List;
import foo.sample.db.auto.ref.model.CatvSp許諾;
import foo.sample.db.auto.ref.model.CatvSp許諾Example;
import foo.sample.db.auto.ref.model.CatvSp許諾Key;

public interface CatvSp許諾Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    long countByExample(CatvSp許諾Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    List<CatvSp許諾> selectByExample(CatvSp許諾Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATV_SP許諾
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    CatvSp許諾 selectByPrimaryKey(CatvSp許諾Key key);
}