package foo.sample.db.auto.ref.crud;

import java.util.List;
import foo.sample.db.auto.ref.model.商品区分マスタ;
import foo.sample.db.auto.ref.model.商品区分マスタExample;
import foo.sample.db.auto.ref.model.商品区分マスタKey;

public interface 商品区分マスタMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    long countByExample(商品区分マスタExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    List<商品区分マスタ> selectByExample(商品区分マスタExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 商品区分マスタ
     *
     * @mbg.generated Wed Dec 26 15:29:57 JST 2018
     */
    商品区分マスタ selectByPrimaryKey(商品区分マスタKey key);
}